### ISSUE TITLE
Spellings with supralinear strokes are not searchable

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#102]
ⲭⲣⲓⲥⲧⲟⲥ is found, but copy-pasting any of its variant spellings containing supralinear strokes (ⲭⲣⲥ︦, ⲭ︤ⲣ︦ⲥ︥) into the "Quick search" field and searching for them delivers nothing.

**Comment by amir-zeldes** [comment]
Fixed in 4708453db12412e5626ceb3b4cb32de1f5bcd3eb and deployed
