### ISSUE TITLE
Add "double oblique hyphen" ("⸗") to the virtual keyboard   

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#103]
Exchange the single oblique hyphen with double oblique hyphen on the virtual keyboard. All status pronominal forms have now  "⸗"( see #95).

**Comment by amir-zeldes** [comment]
Hi @phoenix-mossimo , I think it's good they're consistent now, and we could add it to the keyboard, but actually oblique hyphen (and hyphens in general) are ignored in the word form search in the interface. 

This is done so we can let users find e.g. ⲡⲉϫⲉ without having to enter a hyphen, or without knowing which hyphen glyph we might be using. Linking from Scriptorium also just lets you click on something like ⲡⲉϫⲉ or ⲛⲁⲉⲓⲁⲧ even though they don't have hyphens in the corpus. They can still enter ⲛⲁⲉⲓⲁⲧ⸗ into the search form, but it has then same effect as searching for ⲛⲁⲉⲓⲁⲧ:

https://coptic-dictionary.org/results.cgi?quick_search=ⲛⲁⲉⲓⲁⲧ

https://coptic-dictionary.org/results.cgi?quick_search=ⲛⲁⲉⲓⲁⲧ⸗
