### ISSUE TITLE
ⲡⲉ has incorrect cf. and a typo

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#104]
Unsure whether I already reported this: observe https://coptic-dictionary.org/entry.cgi?tla=C2788

typo: encltic 
incorrect cf.: cf. ⲛⲉ Kopula sg. m. (it's plural)

**Comment by m-linssen** [comment]
There's more to it than this: compare these three entries


ⲧⲉ | S | CF9957 | Dem. Pron. Kopula f. sg.
Dem Pron, and only refers to: cf. ⲡⲉ Kopula sg. m.

ⲡⲉ | S | CF7412 | Pron. m.
Pron, no mention of copula, nor sg/pl, and refers to cf. ⲛⲉ Kopula sg. m. cf. ⲧⲉ Kopula sg. f. (of which NE isn't singular, indeed)

ⲛⲉ | S | CF6534 | Pron. pl.
Pron, pl, no mention of copula

So, many inconsistencies. Dem Pron or Pron? Copula or not? And singular/plural for PE. And one incorrect cf.

This one strikes me as familiar although I don't recall being this elaborate; I've searched through open and closed issues but couldn't find any (might be due to my lack of familiarity with web-github)

**Comment by phoenix-mossimo** [comment]
> Unsure whether I already reported this: observe https://coptic-dictionary.org/entry.cgi?tla=C2788. typo: encltic; incorrect cf.: cf. ⲛⲉ Kopula sg. m. (it's plural)

Corrected 

> There's more to it than this: compare these three entries

Corrected. All three entries follow the same pattern now: 

```
      <entry xml:id="C4007">
        <form type="lemma" xml:id="CF9956"><orth>ⲧⲉ</orth></form>
        <form xml:id="CF9957"><orth>ⲧⲉ</orth></form>
        <gramGrp>
          <pos>Dem. Pron.</pos>
          <subc>Kopula</subc>
          <gen>f.</gen>
          <number>sg.</number>
        </gramGrp>
        <xr type="cf">
          <ref target="#ⲡⲉ">Kopula sg. m.</ref>
        </xr>
        <xr type="cf">
          <ref target="#ⲛⲉ">Kopula pl.</ref>
        </xr>
        <sense>
          <cit type="translation" xml:lang="de">
            <quote>Kopula, fem. sg.</quote>
          </cit>
          <cit type="translation" xml:lang="en">
            <quote>copule, fem sg.</quote>
          </cit>
          <cit type="translation" xml:lang="fr">
            <quote>copule, fém sg.</quote>
          </cit>
          <cit>
            <bibl>CD 391b; CED 177; KoptHWb 217; DELC 208a; ChLCS 55a</bibl>
          </cit>
        </sense>
      </entry>
```
