### ISSUE TITLE
What's the idea on pronouns?

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#106]
I am missing quite a few pronouns, and now making my own:

ⲡⲉϥ | = ⲡⲁ- + ⲛⲧⲟϥ | his
ⲧⲉϥ | = ⲧⲁ- + ⲛⲧⲟϥ | his(F)
ⲛⲉϥ | = ⲛⲁ- + ⲛⲧⲟϥ | his(PL)
ⲛⲉⲕ | = ⲛⲁ- + -ⲕ | your(PL)
ⲧⲱⲧⲛ | = ⲧⲱ⸗ + '-ⲧⲛ | yours(F.PL)
ⲧⲉⲧⲛ | = ⲧⲁ- + -ⲧⲛ | your(F.PL)
ⲡⲉⲧ | = ⲡⲉ + ⲉⲧ- | he-who
ⲧⲟⲩ | = ⲧⲁ- + ⲩ | your(F)
ⲛⲧⲱⲧⲛ | = ⲛⲧⲱ⸗ + '-ⲧⲛ | you(PL)
ⲡⲉⲕ | = ⲡⲁ- + -ⲕ | your
ⲛⲟⲩⲟⲩ | = ⲛⲟⲩ⸗ + -ⲟⲩ | their(PL)
ⲧⲱⲟⲩ | = ⲧⲱ⸗ + -ⲟⲩ | their(F)

I'll create a separate index for these and link to KELLIA from the lemma it contains.
Needless to say, this is extra work, a little far from perfect, and actually the only exception I've made so far to the rule: link to KELLIA for each and every single lemma in Thomas. Save for the names, of course - I can live with that

So my question is: what is your point of view on pronouns?

**Comment by amir-zeldes** [comment]
The Coptic Scriptorium analyzer treats these as a single possessive article, similar to regular p, t, n.

Additionally, some of the forms don't segment well, especially pou, which is not really pa+u (etymologically or synchronically), and in any case not segmenting them makes life easier for subsequent tagging (one less pe, f to disambiguate, as both can be many things). Incidentally, this is the same analysis found in Layton's grammar, which is the basis of much of the grammatical analysis in the Scriptorium corpora and tools.

**Comment by m-linssen** [comment]
Fair enough Amir, there's a thin line between dictionary and grammar I think. I'll continue to create my own then, as my translation is (meant to be) of a more detailed level than your segmenting / tagging
