### ISSUE TITLE
ⲃⲱ ⲛⲉⲗⲟⲟⲗⲉ male?

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#107]
https://coptic-dictionary.org/entry.cgi?tla=C657 labels "vine" as male, however it is female

https://coptic-dictionary.org/entry.cgi?tla=C651 - ⲉⲗⲟⲟⲗⲉ, "grape", is male
https://coptic-dictionary.org/entry.cgi?tla=C323 - ⲃⲱ, "tree", is female

ⲃⲱ ⲛ ⲉⲗⲟⲟⲗⲉ, "Tree of grape" thus would seem to be female, not male. Crum doesn't specify gender in his II. on page 55a

**Comment by phoenix-mossimo** [comment]
Yes, ⲃⲱ, Egyptian bA.t is feminine: http://aaew.bbaw.de/tla/servlet/GetWcnDetails?u=guest&f=0&l=0&wn=52960&db=0

Respectively ⲃⲱ ⲛ ⲉⲗⲟⲟⲗⲉ, is feminine (Westendorf, p. 34). Corrected.
