### ISSUE TITLE
Typo: from vs form

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#110]
https://coptic-dictionary.org/results.cgi?coptic=%E2%B2%81%CF%A9&dialect=any&pos=any&definition=&def_search_type=exact+sequence&lang=any

contains 'from' in the reference to ⲁϩ-

And ⲁϩ- itself, https://coptic-dictionary.org/entry.cgi?tla=C282, does as well

**Comment by phoenix-mossimo** [comment]
corrected with V 1.5
