### ISSUE TITLE
Entry missing for e- meaning "if"

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#112]
@phoenix-mossimo there is a missing, unusual usage of e-, meaning "if" which is mentioned very briefly in CD 52B, but is also listed in Layton's grammar (§346) as a variant of the conditional base. It is only unambiguously identifiable in negation, since unlike the circumstantial, it takes negation with tm-, e.g.:

ektmsO "if you don't drink"

See examples here:

https://corpling.uis.georgetown.edu/annis/?id=11ad515d-54b9-438c-868f-e9d1f52155a4

Should this be added as an entry? Or a form of erSan? I think Layton means it's functionally equivalent to erSan, but I don't know if it should really be considered a morphological form of the same entry.

**Comment by phoenix-mossimo** [comment]
Thanks.  **e-f-San** is Late Egyptian conditional **jr jw.f Hr (+ Inf.)**, **e-f-** is Demotic conditional **jw.f (+Infinitive)**. These forms probably come from different dialects.  As the use of dialectal forms is not clear (Crum referes to "Monastery of Epifanius at Thebes" (Winlock)), for now only Sahidic as dialect provided. Also except Crum, only Cherix mentions the use of this forms as the conditional. 

I created a new entry, with IDs not yet assigned:    
```
       <entry>
        <form type="lemma">
          <usg type="geo">S</usg>
          <orth>ⲉⲣⲉ-</orth>
          <gramGrp>
            <pos>Verbalpräfix</pos>
            <subc>Status nominalis</subc>
          </gramGrp>
        </form>
        <form type="inflected">
          <usg type="geo">S</usg>
          <orth>ⲉⲣⲉ-</orth>
          <gramGrp>
            <pos>Verbalpräfix</pos>
            <subc>Status nominalis</subc>
          </gramGrp>
        </form>
       <form type="inflected">
          <usg type="geo">S</usg>
          <orth>ⲉⲣ-</orth>
          <gramGrp>
            <pos>Verbalpräfix</pos>
            <subc>Status nominalis</subc>
          </gramGrp>
        </form>
 <form type="inflected">
          <usg type="geo">S</usg>
          <orth>ⲉ⸗</orth>
          <gramGrp>
            <pos>Verbalpräfix</pos>
            <subc>Status pronominalis</subc>
          </gramGrp>
        </form>
        <xr type="cf">
          <ref target="#ⲉⲣϣⲁⲛ">Partikel des Konditionalis</ref>
        </xr>
        <sense>
          <ref type="Greek">ἐάν</ref>
          <cit type="translation" xml:lang="de">
            <quote>wenn [Verbalpräfix des Konditionalis]</quote>
          </cit>
          <cit type="translation" xml:lang="en">
            <quote>if [verbal prefix of the conditional]</quote>
          </cit>
          <cit type="translation" xml:lang="fr">
            <quote>si, quand [préfixe verbal du conditionnel]</quote>
          </cit>
          <cit>
            <bibl> CD 52b, ChLCS 10b</bibl>
          </cit>
        </sense>
      </entry>
```

**Comment by amir-zeldes** [comment]
Thanks! All of the texts showing this in ANNIS are ostensibly Sahidic, so I think the dialect information is supported (there are quite a few unambiguous examples with negation in 'tm')
