### ISSUE TITLE
DH Awards 2019 Logo on the title page 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#117]
Maybe it makes sense to put the DH Awards 2019 Logo on the CDO title page?

![](http://dhawards.org/wp-content/uploads/2020/03/DHAwards2019-tool.png) 

Not that it is very fancy, but anyway :-)

**Comment by amir-zeldes** [comment]
Good idea, added and deployed.

**Comment by phoenix-mossimo** [comment]
Hm, how about putting it to the Top bar, next to Kellia? In the bottom are the project participants. Also - just the black field with the white script (as above), without white margins, this would match the color pattern of the top bar.

**Comment by ctschroeder** [comment]
Top bar is fine with me. I see I've been assigned the issue. I created a branch with the intention of making the change myself, but I realized it will take more time than I have to get up to speed on the CSS and make the change. That's fine.

**Comment by amir-zeldes** [comment]
OK, I put it at the top now, let me know if this looks good and I'll push and close.

**Comment by phoenix-mossimo** [comment]
Looks better for me, only that now there are three different "blacks" in the top bar: 

"Home"  button:  rgb (8, 8,8,) #080808
"DH-Awards" button:  rgb (0, 0, 0) #000000
The rest of the bar: rgb (34,34,34) #222222

The difference is clearly visible on good screens. I would  unify all to one color.

**Comment by amir-zeldes** [comment]
I can change the 'home' button to be pitch black like the DH Awards logo, but I wouldn't make them all the same: the 'home' is only black when it's selected (the black shows which tab is currently active). Does it look good with just the two blacks now? (you may need to empty cache and reload)

**Comment by ctschroeder** [comment]
Thank you both!  Would it look better or worse with a border like Kellia?

**Comment by ctschroeder** [comment]
(V minor point)

**Comment by amir-zeldes** [comment]
I tried border, but it looks better without IMO

**Comment by phoenix-mossimo** [comment]
Thanks. Can you show the option with the border?

**Comment by amir-zeldes** [comment]
Sure, you can play with the css too if you like:

![image](https://user-images.githubusercontent.com/2188635/79616217-77d29b80-80d2-11ea-865a-27c5257b34d4.png)

I also find this semantically off TBH, since KELLIA is behind the dictionary while the award is just an award, so it makes sense they look different.

**Comment by phoenix-mossimo** [comment]
Ok, lets leave it th way it is
