### ISSUE TITLE
Import of data into spreadsheet: irregular assignment of tables

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#120]
I got an inquiry (@ Fady Ramzy) why e.g. with **C196** the formula (=IMPORTHTML("http://www.coptic-dictionary.org/entry.cgi?tla=C196"; "table"; 1) successfully imports table 1 (orths) and table 2 (senses), while with **C195** table 2 does not work. The reason seems to lie in the way the tables are generated. With **C195** tables 2-8 are assigned to collocations , while senses come only in table 9. 

So the questions are: 

- Is there a way to standardize the table generation, so that orths are always in table 1, collocations - in table 2, senses - in table 3 etc. ? Without an uniform assignment the usefulness of the =IMPORTHTML function is quite questionable.
- Currently "Scruptorium Tag " and cross-references (c.f. ) are not in the tables.  Can we pack all information in tables? 

N.B. To see the tables on the page: Chrome/ Developer Tools/Console: type in
"var i = 1; [].forEach.call(document.getElementsByTagName("table"), function(x) { console.log(i++, x); });"

**Comment by phoenix-mossimo** [comment]
Cool solution. I will extend "Help" section with this info. What about "cf."? Can you pack it into a one-line table? This is a very useful information to be able to export.

**Comment by amir-zeldes** [comment]
It doesn't have to be a table to be exportable via xquery. I just added an id to that div and now you can test it on the dev instance with an xpath expression like `//div[@id='etym']`.
