### ISSUE TITLE
lemma of thesaurus

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#121]
The lemma of thesaurus seems to have the irregular form ⲑⲩⲥⲁⲩⲣⲟⲥ with upsilon as canonical:

https://coptic-dictionary.org/entry.cgi?tla=C9197

Shouldn't the lemma be ⲑⲏⲥⲁⲩⲣⲟⲥ?

**Comment by KaJohn-DDGLC** [comment]
Changed in (upcoming) CCL v1.2

**Comment by phoenix-mossimo** [comment]
Thanks. Lemma form is now ⲑⲏⲥⲁⲩⲣⲟⲥ

```
            <form xml:id="CF22927" type="lemma">
               <orth>ⲑⲏⲥⲁⲩⲣⲟⲥ</orth>
            </form>
```
