### ISSUE TITLE
oxia vs tonus in polytonic Greek letters

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#125]
There is an inconsistency in the unicode characters used for polytonic Greek letters in the dictionary XML: some entries have the normal (modern) Greek tonus characters for the acutes, while others use the extended Greek area oxia characters:

  * Tonus:
    * ή - 400 times in V1.2 RC
    * example: ἀνοχή (line 169281)
  * Oxia:
    * ή - 39 times in V1.2 RC
    * example: ἀναχωρητής (line 168299)

Currently only the tonus version links correctly to Perseus. I could fix that, but I think the correct solution is to choose one of the two accent character types and use only that variant.

**Comment by phoenix-mossimo** [comment]
Do I understand correctly the conventions:

- use modern Greek tonus characters for simple diacritics 
- use oxia characters for combined diacritics?

**Comment by phoenix-mossimo** [comment]
I guess we can close this one. Closed with V1.2
