### ISSUE TITLE
Deprecated Greek-Coptic enties are still shown

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#128]
Note that `change="#deprecated #v1.2"` has been applied to the "entry" element as well (not only "form"), which means that the whole entry should not be imported / shown.

**Comment by amir-zeldes** [comment]
Yes, I had assumed as much, and I think it is already implemented this way. Do you see an entry in the interface which should be deprecated?

**Comment by phoenix-mossimo** [comment]
Yes, TLA lemma nos. C8218, C8337, C8520, C8723, C8833, C8879, C9093, C9386, C9472, C9947, C10078, C10389, C10539, C10612, C10752, C10889, C10912, C10924, C11055, C11261, C11270.

**Comment by amir-zeldes** [comment]
Oh, yes, sorry - I had made them not searchable (so "ⲁⲙⲫⲓⲃⲟⲗⲓⲁ" found nothing), but I did leave them findable using the TLA ID. I think I remember we already had this discussion once, you want them totally gone, right? I have now removed them completely from the DB, so there's no way to see them in the interface.

https://corpling.uis.georgetown.edu/coptic-dictionary-dev/entry.cgi?tla=C8218

https://corpling.uis.georgetown.edu/coptic-dictionary-dev/results.cgi?quick_search=%E2%B2%81%E2%B2%99%E2%B2%AB%E2%B2%93%E2%B2%83%E2%B2%9F%E2%B2%97%E2%B2%93%E2%B2%81
