### ISSUE TITLE
Display sense IDs

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#129]
The new feature of V 1.2 are the sense IDs, which are supposed to facilitate the linking of CCL to the databases of semantic relations such as Coptic WordNet. They could be displayed on the CDO UI as well, e.g.: 

C3092 (ⲣⲱⲙⲉ)

1. Sense-ID: CS3540
  | (En) | man, human being
  | (Fr) | homme, être humain
  | (De) | Mann, Mensch

2. Sense-ID: CS3541
  | (En) | kinsman, friend, serving-man
  | (Fr) | parent, ami, serviteur
  | (De) | Verwandter, Freund, Diener

**Comment by amir-zeldes** [comment]
This should be possible to do, but are we sure we don't want to use a tooltip or something? It seems to me that this will take up a bit of screen real estate, and 99% of users probably don't need to use these IDs, so we could just hide them and only display them on hover or something. What do you think?

**Comment by phoenix-mossimo** [comment]
Ok, lets try tooltip

**Comment by amir-zeldes** [comment]
OK, take a look on dev now and let me know what you think

**Comment by phoenix-mossimo** [comment]
cool. works. Closed with V 1.2
