### ISSUE TITLE
Entries missing from CD p.388

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#135]
I can't find these entries in CDO, which all seem to come from Crum p. 388:

ⲥⲉϭⲉ
ⲥⲉⲉⲓϭⲉ
ⲥⲟϭ
ⲥⲱϭ
ⲥϭⲏⲣ
...

**Comment by amir-zeldes** [comment]
Also ⲥϭⲣⲁϩⲧ from the following page

**Comment by phoenix-mossimo** [comment]
This is unfortunately an old issue #45
