### ISSUE TITLE
Strip the query of "-" and "="

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#16]
I.e. if the user enters "x-" or "x=", just look for "x". 

There is a number of reasons for that. 

1. Looking for "ⲙⲛⲧ-" we find nothing (I copy-pasted characters from https://corpling.uis.georgetown.edu/coptic-dictionary/entry.cgi?entry=1910&super=873 ) into the search form and looked for them again. 

2. Clicking on ⲙⲛⲧ- or ⲁⲧ- (displayed as cross-references with ⲙⲛⲧⲁⲧⲧⲁⲕⲟ) will also find nothing. 

3. I am not sure how consistent is the encoding of inflected forms, i.e. if all inflected forms are given with "-" or "=".

**Comment by amir-zeldes** [comment]
Should this be interpreted as exact match (find exactly 'mnt') or as regex prefix (mnt- means mnt.*)?

**Comment by phoenix-mossimo** [comment]
Not sure with "mnt.*" - it gets all kinds of stuff. Maybe "mnt-*"?

**Comment by amir-zeldes** [comment]
OK, so I understand you want exact match ("mnt-" finds the entry for mnt, not entries for mntatsOtm, mntrmnhHt, ...)

**Comment by phoenix-mossimo** [comment]
Yes, an exact match: e.g. "ⲙⲛⲧ", "ⲁⲧ"
