### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#164]
Hi,

I get:

This server could not prove that it is coptic-dictionary.org; its security certificate expired in the last day. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Monday, 5 April 2021. Does that look right? If not, you should correct your system's clock and then refresh this page.

Proceed to coptic-dictionary.org (unsafe)

**Comment by amir-zeldes** [comment]
Thanks for reporting, it looks like the certificate has expired. We are looking into fixing this!

**Comment by amir-zeldes** [comment]
OK, this error should now be resolved.

**Comment by m-linssen** [comment]
Check!
Tried a few devices, browsers, and incognito modes - all good.
Thanks for the very quick fix!
