### ISSUE TITLE
Definition Search is a simple string match and returns English only (though it searches in target language)

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#168]
1)

It would seem that the search is fairly simple, and just looks for strings in translations - in stead of whole words only.
Please observe https://coptic-dictionary.org/entry.cgi?tla=C7883:

(En)	be in want, needy, diminished
(Fr)	avoir besoin, être dans le besoin, manquer
(De)	benötigen, bedürfen, Not leiden, mangeln, fehlen

In German, part of the string says "bed": bedürfen

Likewise for https://coptic-dictionary.org/entry.cgi?tla=C5649:

(En)	need
(Fr)	avoir besoin de
(De)	bedürfen, nötig haben

Now what do I get when I search for 

https://coptic-dictionary.org/results.cgi?coptic=&dialect=any&pos=any&definition=bed&def_search_type=exact+sequence&lang=any

Exactly that:

You searched definitions matching bed in language any
9 Results
ⲁⲛⲑⲉⲱⲛⲟⲥ	--	flower-garden, bed of flowers
ⲁϩⲉ (ⲛ-)	ⲁϩⲉ (ⲛⲁ⸗)		need
ⲕⲁϣ		--	reed-bed, plantation
ⲗⲟⲗ		--	bed, bench
ⲙⲁ ⲛⲕⲁϣ	--	bed, plantation of reeds
ⲱⲡⲓϣ	--	broad river-bed
ϣⲱⲱⲧ	--	cut, slay, be cut short, want, lack
ϭⲗⲟϭ	--	bed, bier
ϭⲣⲱϩ	--	be in want, needy, diminished

I have left ϣⲱⲱⲧ for yourselves to figure out, although there won't be any surprise there.

2)

Oddly, I can look for German specifically:

https://coptic-dictionary.org/results.cgi?coptic=&dialect=any&pos=any&definition=bed&def_search_type=exact+sequence&lang=de

And all it returns is English - though with the exact three words that in German contain the string "bed" in their translation.
Much confusion...

**Comment by amir-zeldes** [comment]
This is a 'bug' or gotcha in basic Python regex: German characters are not included in the boundary detection character set, so the search decides that "bed" before "ürfen" is a complete word :)

I replaced it with a Unicode aware regex, it should work as expected now:

https://coptic-dictionary.org/results.cgi?coptic=&dialect=any&pos=any&definition=bed&def_search_type=exact+sequence&lang=any
