### ISSUE TITLE
Greek words: open up Perseus entry in new window

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#169]
**Is your feature request related to a problem? Please describe.**
Clicking a Perseus link, e.g. the one in https://coptic-dictionary.org/entry.cgi?tla=C10988, opens Tufts in the current window of the CDO. On mobile, the back navigation after that is cumbersome as Tufts always requires at least one more click for the dictionary of choice (and I tend to click a bit here and there in Perseus anyway, digging deeper for related entries)

**Describe the solution you'd like**
I'd love a default navigation to Perseus via a new window. These days the choice would default to opening a new tab in the browser instead of opening an entirely new browser. On Chrome & Android that could be a new tab in the current group and then one could kill the entire group at some point - dunno really about pros and cons there, I'd be happy with just a new tab as well

**Describe alternatives you've considered**
Of course I can right-click the link and choose to open it in a new window myself. Still, after a thousand times of clicking a Perseus link, I think I haven't managed more than a dozen times to do so. Victim of pleasant UX, perhaps, or lazy or distracted LOL

**Additional context**
This is a very fine, to the point and simple template! Most excellent, thank you very much.
With regards to overall strategy / UX, perhaps all extra-CDO links should be treated in the same way?

**Comment by amir-zeldes** [comment]
There is a fairly established position in Web Design theory that forcing users to open links in a new tab should generally be avoided - for some example discussions and rationale see:

https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187
https://www.nngroup.com/articles/new-browser-windows-and-tabs/

However I am by no means a doctrinaire - if there is a substantial group of users who thinks this would make CDO better, it's certainly easy to implement. 

Any opinions @dwerning @simondschweitzer @KaJohn-DDGLC @ctschroeder @somiyagawa @phoenix-mossimo ?

**Comment by simondschweitzer** [comment]
I tend more to think that we should follow the standards of web design theory. The links you sent, dear @amir-zeldes, are convincing. It would be weird if the website deviates from the UX. But every user request is important, especially if it comes from a power user, dear @m-linssen ;-) I'm curious what the others think about this question. Anyway, there are browser extensions that allow opening links in new tabs for self-defined pages, e.g. https://chrome.google.com/webstore/detail/open-links-in-new-tab/bbccifaebcaangidpmojlooininapefb Would this perhaps be a solution?

**Comment by m-linssen** [comment]
> I tend more to think that we should follow the standards of web design theory. The links you sent, dear @amir-zeldes, are convincing. It would be weird if the website deviates from the UX. But every user request is important, especially if it comes from a power user, dear @m-linssen ;-) I'm curious what the others think about this question. Anyway, there are browser extensions that allow opening links in new tabs for self-defined pages, e.g. https://chrome.google.com/webstore/detail/open-links-in-new-tab/bbccifaebcaangidpmojlooininapefb Would this perhaps be a solution?

I like the suggestion Simon, but the extension you suggest is malfunctioning, alas. A much better one is https://chrome.google.com/webstore/detail/open-in-new-tab/cplillmhmcegjlhcbedmgmalbgjpmlkh, yet these work on the basis of links from a site, not to a site.
I will make the story short, and then you may wonder why you didn't think of it yourselves. I waited a bit for others to chime in, but 2 weeks will do:

The first site linked is fairly myopic, the second is a lot better. Yet both talk about interrupting processes, and I will cite (even) the first:

At the end, it says "Exceptions - The only time it is recommended that you open a link in a new tab is when opening in the same screen would interrupt a process (e.g. when a user is filling out a form or viewing a video)." - this is exactly what I mean, **by opening the external link in the same tab as the CDO, I suddenly have Perseus TUFTS as my main "process"**

That behaviour is entirely unexpected, as all links to Crum / CoptOT open in a new window, and rightly so, because doing otherwise would interrupt the main process of "doing stuff in CDO".
Likewise, for TUFTS - and in theory you could have any other online dictionary and link to it, and all of them would open up in different tabs, and **links to those sites would remain to be opened in that tab, exactly as is the case with Crum / CoptOT**

_So, to make it as concise a "problem" as it is: why do you open links to CoptOT in a new Window, whereas you insist on opening links to Tufts in the same?_

Martijn Linssen

**Comment by amir-zeldes** [comment]
> why do you open links to CoptOT in a new Window

If you want a factual answer to that, the answer is probably that different people with different philosophies and habits worked on the interface at different times, so it is not 100% consistent. TBH my instinct is to fix that by making CoptOT also not default to a new window, but I certainly don't want to punish a feature request by changing another thing a user is happy with :)

So far I read @simondschweitzer as lukewarm-negative on this and @m-linssen as positive, but given the general lack of other comments one way or another, I'm inclined to just close this as wontfix... The main reason I sympathize with the recommendations in the links I sent is that it is very easy to open things in a new tab (right click, or long click on mobile), while NOT doing so when the UI forces it is actually tricky. So the status quo might be the most flexible, assuming others don't feel strongly otherwise. 

If this pops up again or someone wants to fight for the other position, feel free to reopen of course.

**Comment by m-linssen** [comment]
Well, apart from hardly ever avoiding a fight or battle, I like to pick those that I can win (it does get quite busy otherwise, really)

In all seriousness: as a middle aged old fart I live by "if it isn't recognised as a problem, then perhaps it takes too much time and energy to turn it into one (by raising awareness and such) - and if it really is a problem, then it will become recognised as such in due time and it will get solved eventually. And if not, well - then not". I'm not as young as Greta anymore and use my energy much more efficiently these days (please don't ask my wife for a second opinion)

So, I reluctantly (LOL) agree. I use CoptOT as a sandbox but that's really just me being overly lazy; my own OCR Crum is a lot better - so the current behaviour fits me but perhaps I have developed that behaviour in response to the behaviour of the CDO?!

Let's see what happens when another dictionary (or two) get added. The difference between CoptOT and Tufts is that CoptOT navigates within its own window, whereas Tufts uses the browser - or rather, it operates at the same level as the CDO operates. So perhaps it could be considered to open CoptOT in the current window, and Tufts in a new one - for reasons of indeed "interfering with the process"

But let's leave all these musings to whoever in the future wants or needs to pick this up

Thanks

**Comment by m-linssen** [comment]
I'll pretend to not notice that suddenly CoptOT opens in the same window.
IT systems are marvelous, really - they make changes all by themselves!

**Comment by amir-zeldes** [comment]
I swear it wasn't me! Nothing has been changed following this issue, scouts' honor :)
