### ISSUE TITLE
Copula consistency in terms of definition and gender / number / general order

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#173]
**Describe the bug**
The nexus pronoun copula description(s) is very inconsistent, making it nigh impossible to find all three.
It also doesn't help that the crossref targets are in German, but that is another issue

**To Reproduce**
Observe (part of) the XML entries for all three:

ⲛⲉ

    <sense xml:id="CS2753">
      <cit type="translation"><quote xml:lang="de">Kopula des Plurals im Nominalsatz</quote>
      <quote xml:lang="en">plural copula (nexus pronoun)</quote>
      <quote xml:lang="fr">copule du pluriel</quote>
ⲡⲉ

    <sense xml:id="CS3188">
      <cit type="translation"><quote xml:lang="de">Kopula sg. m. im Nominalsatz</quote>
      <quote xml:lang="en">sg. masc. copula (nexus pronoun)</quote>
      <quote xml:lang="fr">copule m. sg.</quote>
ⲧⲉ

    <sense xml:id="CS4553">
      <cit type="translation"><quote xml:lang="de">Kopula, fem. sg.</quote>
      <quote xml:lang="en">copule, fem sg.</quote>
      <quote xml:lang="fr">copule, fém sg.</quote>

A few issues there, first is the English feminine copula saying copule.
What are the rules for abbreviations of gender and number? Masc. or m.?
What is their order - first the gender and then the number or vice versa?
Why is Nominalsatz included in only two entries, likewise for nexus pronoun?

Harmonise it a bit, but most importantly fix the spelling error for copule - that one is very hard to find this way.
What you present now in each language is the following, going by the order of masculine, feminine and plural:

German
Kopula sg. m. im Nominalsatz
Kopula, fem. sg.
Kopula des Plurals im Nominalsatz

French
copule m. sg.
copule, fém sg.
copule du pluriel

English
sg. masc. copula (nexus pronoun)
copule, fem sg.
plural copula (nexus pronoun)

**Expected behavior**
I would expect a very nice and neat and consistent use of attributes, e.g.:

Main attribute at the very start: copula. Secondary attribute (nexus pronoun) follows, gender and number follow after that, and always in the same order: gender first, number second.

So, for instance:

NOT:
German
Kopula sg. m. im Nominalsatz
Kopula, fem. sg.
Kopula des Plurals im Nominalsatz

BUT INSTEAD:
Kopula (im Nominalsatz) m. sg.
Kopula (im Nominalsatz) f. sg.
Kopula (im Nominalsatz) pl.

NOT:
French
copule m. sg.
copule, fém sg.
copule du pluriel

BUT INSTEAD:
copule (???) m. sg.
copule (???) f. sg.
copule (???) pl.

NOT:
English
sg. masc. copula (nexus pronoun)
copule, fem sg.
plural copula (nexus pronoun)

BUT INSTEAD:
copula (nexus pronoun) m. sg.
copula (nexus pronoun) f. sg.
copula (nexus pronoun) pl.

You can now immediately see that there is something missing in the French description

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by amir-zeldes** [comment]
Fixed
