### ISSUE TITLE
Bad example sentence for the entry C6475

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#174]
Word you searched for in the dictionary (in Coptic):

ϩⲱⲱⲕ <REPLACE THIS WITH YOUR ENTRY>

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C6475 <REPLACE THIS WITH YOUR ENTRY>

Bad example sentence (insert your example):

All of them

<EXPLANATION WHY THIS IS BAD>

Seems like they use the verb instead of the noun (my Coptic still isn't very good)

**Comment by amir-zeldes** [comment]
Thanks for reporting - I think this might be the only good example I can find of it in our data:

https://corpling.uis.georgetown.edu/annis/?id=8d33d6a1-7690-40a2-aac0-bb52374ca9a8

So we can use that one instead (will take a bit of time to update) - but if you or anyone know more examples that are available in Scriptorium data, please post to this issue!

**Comment by m-linssen** [comment]
The spelling you use is labelled rare, Amir - the more usual one has 7 occurrences.Can't seem to get you the link, so here's the query:lemma=‎"ϩⲱⲕ‎" _=_ pos=‎"N‎"My Coptic isn't really my forte LOL - use at your own risk 😉
-------- Original message --------From: Amir Zeldes ***@***.***> Date: 24/06/2021  17:05  (GMT+01:00) To: KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary] Bad example sentence for the entry C6475
  (#174) 
Thanks for reporting - I think this might be the only good example I can find of it in our data:
https://corpling.uis.georgetown.edu/annis/?id=8d33d6a1-7690-40a2-aac0-bb52374ca9a8
So we can use that one instead (will take a bit of time to update) - but if you or anyone know more examples that are available in Scriptorium data, please post to this issue!

**Comment by amir-zeldes** [comment]
OK, we now have a mechanism for introducing manually selected examples (e71aa33) when errors are identified. I will update the issue template to let users suggest examples as well. This particular error should now be fixed.
