### ISSUE TITLE
Bad example sentence for the entry ⲛⲁ- / C2354

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#175]
Word you searched for in the dictionary (in Coptic):

ⲛⲁ- <REPLACE THIS WITH YOUR ENTRY>

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C2354 <REPLACE THIS WITH YOUR ENTRY>

Bad example sentence (insert your example):

All examples are bad, they are futurum or datives. Possibilities are endless of course, with these two letters! I'd check the others as well

Notes:

<EXPLANATION WHY THIS IS BAD>

See above

**Comment by amir-zeldes** [comment]
Fixed using the mechanism in e71aa33c
