### ISSUE TITLE
Bad example sentence for the entry <ENTRY>

### ISSUE THREAD

**Issue by dilata69** [KELLIA/dictionary#178]
Word you searched for in the dictionary (in Coptic):

ⲙⲣⲱ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C2008

Bad example sentence (insert your example):

ⲛⲁⲓ ⲉϣϣⲉ ⲉϣⲧⲙⲣⲱⲟⲩ ⲛⲁⲓ ⲉⲧϣⲟⲣϣⲣ ⲛϩⲉⲛⲏⲓ ⲧⲏⲣⲟⲩ ⲉⲩϯⲥⲃⲱ ⲛⲛⲉⲧⲉⲙⲉϣϣⲉ ⲉⲧⲃⲉⲟⲩⲙⲛⲧⲙⲁⲓϩⲏⲩ ⲛϣⲗⲟϥ .
whose mouths must be stopped; men who overthrow whole houses, teaching things which they ought not, for dishonest gain's sake.
56_Titus_1 (urn:cts:copticLit:nt.titus.sahidica:1)

Notes:

<EXPLANATION WHY THIS IS BAD>

Better examples:
This example belongs to the word ⲣⲟ, ⲣⲱⲟⲩ mouth.

**Comment by amir-zeldes** [comment]
Thanks for reporting, this example has now been removed!
