### ISSUE TITLE
Bad example sentence for the entry ⲥⲓⲣ

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#182]
Hi Amir, I can be brief: there are no examples of ⲥⲓⲣ being used in the sense of leaven, only butter and cheese - so all examples under

https://coptic-dictionary.org/entry.cgi?tla=C3686

point to the word that is under

https://coptic-dictionary.org/entry.cgi?tla=C3685

Manuscriptroom has 9 hits in 8 docs, but there's a fake positive due to automatic tagging in 1 Sam 4:2

https://corpling.uis.georgetown.edu/annis/?id=b36055dc-1051-4d42-a409-64c05a8d2d1e

ⲥⲉⲣⲉ there is in fact ⲥⲉⲣ-, the nominal of ⲥⲱⲣ, C3694

I would be very interested in the Fayyumic Mat 13:33 that Crum mentions! Do you have any idea where I could find such?

Cheers,

Martijn

**Comment by amir-zeldes** [comment]
Hmm, this is a tricky one, because both are nouns (so even correct POS tagging doesn't guarantee disambiguation), and according to the dictionary, ⲥⲁⲓⲣⲉ is actually a possible a possible form of the other ⲥⲓⲣ lemma (I guess both are derived from Hebrew/Canaanite שעור). Because this is a rare word, it is close to impossible to rely on the lemmatizer to get this right, however the large OT and NT corpora are fully automatically tagged, so fixing this would not be straightforward.

For the dictionary, the easiest fix would be to force using correct examples. Have you found any correct examples of the first lemma? If so, we have a mechanism of listed examples which I could use to force the dictionary to prefer those (once there are 3, it won't look for any others). I'd just need the URNs.

For Fayyumic I'm afraid I can't say much, I would love to have more dialects in Scriptorium, but it will be a while before we get there. If anyone else on this repo knows a good Fayyumic resource, please chime in.

**Comment by m-linssen** [comment]
Hi Amir, tnx.Yes, sure, doing this automatically would be mind boggling - I just reported the bad examples I doubt that anyone uses ⲥⲓⲣ without using a variant - homonyms need to be different enough in order to peacefully coexist; Crum likely got that wrong, he was wrong about ⲥⲉⲣϭⲁⲙⲟⲩⲗ as well, that only exists as an artificial "caltrop", not a plant (if you can prove me wrong there, please do! and I will be very happy)The Hypostasis of the Archeons uses ⲥⲓⲣ, yet unfortunately the translators didn't get it and interpreted it as "mount Sir".Anywayorig=‎/ⲥⲁⲉ?ⲓⲣⲉ?‎/ will do the trick for the first ⲥⲓⲣ:https://corpling.uis.georgetown.edu/annis/?id=7637071a-9947-49e8-a509-9c6be255967dCheers, Martijn
-------- Original message --------From: Amir Zeldes ***@***.***> Date: 24/11/2021  16:20  (GMT+01:00) To: KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary] Bad example sentence for the entry ⲥⲓⲣ (Issue #182) 

Hmm, this is a tricky one, because both are nouns (so even correct POS tagging doesn't guarantee disambiguation), and according to the dictionary, ⲥⲁⲓⲣⲉ is actually a possible a possible form of the other ⲥⲓⲣ lemma (I guess both are derived from Hebrew/Canaanite שעור). Because this is a rare word, it is close to impossible to rely on the lemmatizer to get this right, however the large OT and NT corpora are fully automatically tagged, so fixing this would not be straightforward.

For the dictionary, the easiest fix would be to force using correct examples. Have you found any correct examples of the first lemma? If so, we have a mechanism of listed examples which I could use to force the dictionary to prefer those (once there are 3, it won't look for any others). I'd just need the URNs.

For Fayyumic I'm afraid I can't say much, I would love to have more dialects in Scriptorium, but it will be a while before we get there. If anyone else on this repo knows a good Fayyumic resource, please chime in.

**Comment by m-linssen** [comment]
Having said that, orig_group=‎/.*ⲥⲓⲣ.*‎/leads to nothing useful, only 17 results and almost all are mere names. Of course there's automatic tagging involved, but you've (just) passed the one million tokens so this does say something.And there are 67 occurrences of 'leaven' in the WEB OT, and lemma=‎"ⲑⲁⲃ‎" | ‎"ⲁⲧⲑⲁⲃ‎" | ‎"ⲕⲱⲃ‎"finds 60 of them - so that's a great coverage, even though we can't just compare words on a like for like basis.Yet without further ado, I think we can agree on the futility of getting to find examples of ⲥⲓⲣ for the CDOBy the way, the first query must be pretty resource hungry, I don't usually use wild cards. So rest assured I won't hog the system ;-)Cheers
-------- Original message --------From: me ***@***.***> Date: 24/11/2021  17:11  (GMT+01:00) To: KELLIA/dictionary ***@***.***>, KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary] Bad example sentence for the entry ⲥⲓⲣ (Issue #182) Hi Amir, tnx.Yes, sure, doing this automatically would be mind boggling - I just reported the bad examples I doubt that anyone uses ⲥⲓⲣ without using a variant - homonyms need to be different enough in order to peacefully coexist; Crum likely got that wrong, he was wrong about ⲥⲉⲣϭⲁⲙⲟⲩⲗ as well, that only exists as an artificial "caltrop", not a plant (if you can prove me wrong there, please do! and I will be very happy)The Hypostasis of the Archeons uses ⲥⲓⲣ, yet unfortunately the translators didn't get it and interpreted it as "mount Sir".Anywayorig=‎/ⲥⲁⲉ?ⲓⲣⲉ?‎/ will do the trick for the first ⲥⲓⲣ:https://corpling.uis.georgetown.edu/annis/?id=7637071a-9947-49e8-a509-9c6be255967dCheers, Martijn-------- Original message --------From: Amir Zeldes ***@***.***> Date: 24/11/2021  16:20  (GMT+01:00) To: KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary] Bad example sentence for the entry ⲥⲓⲣ (Issue #182) 

Hmm, this is a tricky one, because both are nouns (so even correct POS tagging doesn't guarantee disambiguation), and according to the dictionary, ⲥⲁⲓⲣⲉ is actually a possible a possible form of the other ⲥⲓⲣ lemma (I guess both are derived from Hebrew/Canaanite שעור). Because this is a rare word, it is close to impossible to rely on the lemmatizer to get this right, however the large OT and NT corpora are fully automatically tagged, so fixing this would not be straightforward.

For the dictionary, the easiest fix would be to force using correct examples. Have you found any correct examples of the first lemma? If so, we have a mechanism of listed examples which I could use to force the dictionary to prefer those (once there are 3, it won't look for any others). I'd just need the URNs.

For Fayyumic I'm afraid I can't say much, I would love to have more dialects in Scriptorium, but it will be a while before we get there. If anyone else on this repo knows a good Fayyumic resource, please chime in.

**Comment by amir-zeldes** [comment]
I had a look at this, and as far as I can tell the relevant reading of C3686 is not attested in current Scriptorium data, and the Biblical citation from Crum is Fayyumic only (it's ⲑⲁⲃ in Sahidic), so there is no way to get a viable example until one of those Sahidic sources from Crum is added. I think the best solution is to not have citations for this word at present.

@simondschweitzer @dwerning @ctschroeder @lancealanmartin note that I have added a convention to the citation override table to support this: if you list `ALL` as the value in the forbidden URNs column, no citations will be generated for this TLA ID. This is implemented for C3686, but will only propagate to the interface on the next update. We can leave this issue open as a reminder until then.
