### ISSUE TITLE
Bad example sentence for the entry <ⲥⲛⲁⲧ>

### ISSUE THREAD

**Issue by elliottlash12** [KELLIA/dictionary#183]
Word you searched for in the dictionary (in Coptic):

ⲥⲛⲁⲧ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C3603

Bad example sentence (insert your example):

ⲁⲩⲱ ⲥⲛⲁⲧⲥⲉϥ ⲟⲩⲙⲟⲟⲩ ⲛⲥⲟⲫⲓⲁ ⲥⲛⲁⲧⲙⲉϥ ⲟⲉⲓⲕ ⲙⲙⲛⲧⲥⲁⲃⲉ
With the bread of understanding shall she feed him, and give him the water of wisdom to drink.
71_Sirach_15 (urn:cts:copticLit:ot.sir.coptot:15)

Notes:

In the above example, there are two instances of the sequence ⲥⲛⲁⲧ. The second is wrongly segmented as if it were an instance of the word ⲥⲛⲁⲧ 'fear'. This is wrong. In both cases the sequence ⲥⲛⲁⲧ should be segmented as ⲥ 'she', ⲛⲁ 'will', with the ⲧ being part of the causative main verb: ⲧⲥⲉϥ 'makes him drink', and ⲧⲙⲉϥ 'makes him eat' / 'feeds him'.

Better examples:

<If you have better examples from Scriptorium corpora, please list them here, ideally with the document_cts_urn, chapter and verse numbers>

**Comment by amir-zeldes** [comment]
Thanks for reporting the segmentation and example errors - as far as I can tell, this word is not attested in our Sahidic corpus holdings (Crum cites a single example from an ostracon we do not have digitized), so probably the best solution for the example is to delete the citation. I've also made a note of the segmentation errors, though their correction will only take effect in the data the next time we re-run the automatic tools on the OT corpus.

**Comment by amir-zeldes** [comment]
Fixed
