### ISSUE TITLE
https://coptic-dictionary.org/entry.cgi?tla=C11007 says SUBST, is VERB

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#184]
It's a quickie

Compare

ⲭⲱⲣⲏⲅⲉⲓ | S | CF30218 | Subst. |   | ANNIS

with

cf. Gr. (DDGLC lemma ID 5572) χωρηγέω  to lead, supply, furnish. verb (Preisigke 2:767?)

**Comment by amir-zeldes** [comment]
It's just not attested in Perseus, is that what you mean? This form seems to be pretty rare, though you can find that Greek lemma here and there:

https://www.trismegistos.org/tm/detail.php?quick=16535

Or maybe it's a variant of this better attested word:

https://el.wiktionary.org/wiki/%CF%87%CE%BF%CF%81%CE%B7%CE%B3%CF%8E

Which however is also not in Perseus. Pinging @KaJohn-DDGLC for an opinion, but I guess there's not too much we can do from our end (I don't think Perseus has Preisigke digitized)

**Comment by amir-zeldes** [comment]
oh, sorry, I see now - that's just an XML error, because it says "Subst." - @simondschweitzer @dwerning can this be added to the corrections for the XML lemma list? Thanks!

**Comment by m-linssen** [comment]
No problem - but I wouldn't label it "an XML error" - it highly likely is labelled as a noun in the database and as such it comes with any carrier - XML, JSON, whatever you'd useYou see, application integration and automated information exchange is what I do for a living. Electronic Data Interchange - unsure that's a familiar term outside of the field, I mostly work for global ***@***.*** @dwerning , if you really do have a separate "XML list" next to the source data, you'll be having a serious issue with double bookkeeping. Single source of truth, Master Data Management - that sort of thingCheers, Martijn
-------- Original message --------From: Amir Zeldes ***@***.***> Date: 09/12/2021  19:38  (GMT+01:00) To: KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary]
  https://coptic-dictionary.org/entry.cgi?tla=C11007 says SUBST, is VERB (Issue
  #184) 
oh, sorry, I see now - that's just an XML error, because it says "Subst." - @simondschweitzer @dwerning can this be added to the corrections for the XML lemma list? Thanks!

**Comment by amir-zeldes** [comment]
The lemma list uses TEI XML's dictionary module as a scaffolding. The dictionary database is then populated automatically from that master XML file, so yes, fixing the XML is the "single source of truth" in this case AFAIK.

**Comment by m-linssen** [comment]
See, I learned something new. That scenario would imply an offensive amount of overhead but storage and computing speed these days are abundantly cheap.As long as you have a single source, anything that works does work reallyIt would still be a data error but at least I now understand what you mean when you call it an XML error and I won't be pesky about it any longer LOL
-------- Original message --------From: Amir Zeldes ***@***.***> Date: 09/12/2021  21:33  (GMT+01:00) To: KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary]
  https://coptic-dictionary.org/entry.cgi?tla=C11007 says SUBST, is VERB (Issue
  #184) 
The lemma list uses TEI XML's dictionary module as a scaffolding. The dictionary database is then populated automatically from that master XML file, so yes, fixing the XML is the "single source of truth" in this case AFAIK.

**Comment by amir-zeldes** [comment]
Fixed
