### ISSUE TITLE
CDO down

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#193]
Hi Amir,

CDO has been down since last evening at the least

Cheers, 

Martijn

**Comment by amir-zeldes** [comment]
Thanks for reporting Martijn - unfortunately our server has been hit by a cyberattack and is still under quarantine. We are working to get it back up as soon as we can.

**Comment by m-linssen** [comment]
Hi Amir,

have you tried switching IP? DDOS usually works with IP address rather than DNS as that's faster and has no dependencies

You'll also have no other option than to block IP addresses that  pass a certain threshold - you can always release them again a day or so later

I'm desperately looking for alternative ways to host the CDO, perhaps reroute it through a site of my own first. This is not a SPOF I seriously considered when creating the Translation!

**Comment by amir-zeldes** [comment]
No, it was not DDOS. In any case, I have now put up a clone of the dictionary and redirected the URL, so its here again:

https://coptic-dictionary.org/

Some functions (ANNIS, Coptic NLP) are sadly still unavailable.
