### ISSUE TITLE
ⲕⲣⲟⲩⲣ means frog

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#195]
... but the definition says unknown. Should we just fix this and put in frog? Or is there some reason to want to mirror Crum 1:1?

@dwerning @simondschweitzer

**Comment by simondschweitzer** [comment]
IMHO, we should fix it, add 'frog' and the bibliographic reference, e.g. Westendorf, page 68. The CDO should not be just a mirror, it should offer the current lexicographic knowledge.
