### ISSUE TITLE
https://coptic-dictionary.org/entry.cgi?tla=C9513 = 9514 (duplicate)

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#197]
Hi guys,

easy one: this really seems duplicate to me, they at least points to the same DDGLC lemma ID 1191

And yes, I'm on it again: Philip this time.
And if you thought Thomas was hazardous material...

**Comment by amir-zeldes** [comment]
It does look that way, but the entries are not quite identical (different form IDs and one extra sense). @dwerning @simondschweitzer and adding @KaJohn-DDGLC since this is Greek. Any preference on which entry to keep?

**Comment by KaJohn-DDGLC** [comment]
It is not a duplicate. C9514 is for our Coptic Lemma ⲕⲟⲥⲙⲓⲕⲟⲥ (DDGLC CL ID: 1379) and C9513 for our Coptic Lemma ⲕⲟⲥⲙⲓⲕⲟⲛ (DDGLC CL ID: 1380). In the first case, the loaned Greek paradigm observed (GPO) is adj sg masc nom, in the second case, the GPO is adj sg neut nom. It constitutes a different Coptic Lemma in our regulations. All the meaning IDs given (ref) are to unique entries in our lexical meanings. 
The relationship between Greek to Coptic Lemma is one-to-many.

**Comment by amir-zeldes** [comment]
Oh, @KaJohn-DDGLC I'm sorry, I'm not sure how I missed that - they're fine then, let's close this issue.

@m-linssen I see they both say "adjective (LSJ 984b)" for the Greek, so they are both adjectives in Greek. Or do you mean the Coptic POS? Coptic has almost no adjectives, so these are morphosyntactically nouns in Coptic. The only exception is the small class of words like ⲁⲥ which are true adjectives.
