### ISSUE TITLE
Certificate expired 

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#199]
It was good till yesterday.
I'd set a reminder, the new one will likely expire in yet another 1.5 years

Good luck

@amir-zeldes

**Comment by amir-zeldes** [comment]
Fixed, thanks for reporting (it should have auto-renewed but there was a bug crashing certbot...)

**Comment by m-linssen** [comment]
Fantastic Amir!Yeah, I always just keep an old fashioned list. I'm DEV again at my current client, had 200 certs to watch at the previous one where I was OPS. An OS update, incomplete app restart, etc: there's always a handful of cert bots that slip throughAnd then some were absolutely business critical and used globally which means negotiations with multiple parties that start weeks in advance, sometimes months, etcAnyway, thanks!!!
-------- Original message --------From: Amir Zeldes ***@***.***> Date: 01/11/2022  21:27  (GMT+01:00) To: KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary] Certificate expired  (Issue #199) 
Fixed, thanks for reporting (it should have auto-renewed but there was a bug crashing certbot...)
