### ISSUE TITLE
Display entries with no compond forms first  

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#2]
Steps to reproduce: 

Search for "ⲉⲓⲣⲉ":  Currently the "head word" "ⲉⲓⲣⲉ" (act; become, befall; do) is hidden somewhere in the middle of the first 100 entries.

Search for "ϫⲓ": the head word "ϫⲓ" is not displayed at all because it is not included in the first 100 entries (see issue #1 )

**Comment by amir-zeldes** [comment]
Fixed in 8e95ba5fbfe9416912dba4add88c8aef243d5153 according to 'related entry' solution from #19
