### ISSUE TITLE
Virtual keyboard

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#20]
How about a virtual keyboard for Coptic input (similar to the one you have in Annis)? 

I was asked a couple of times by people who do not use (or do not know how to install) the Coptic keyboard and the associated font.

**Comment by amir-zeldes** [comment]
Yes, this is a nice idea. I'll need to dig up the code from ANNIS, I think it's just a javascript library.

**Comment by ctschroeder** [comment]
We have it in Github. Hang on.

**Comment by ctschroeder** [comment]
https://github.com/CopticScriptorium/keyboard

**Comment by amir-zeldes** [comment]
Thanks @ctschroeder , that's the file describing the keyboard - I need to have a quick look at the JS framework itself, but it should be doable.

**Comment by amir-zeldes** [comment]
I just got a question from a user about pasting in data in Abraam font etc., which is basically one of many ascii representations of Coptic. This makes me think maybe the better approach is to allow something like Greek Beta code input. We could optionally allow users to input Latin characters and convert them to Unicode Coptic. This might actually be more usable than a virtual keyboard (same thing Perseus does for Greek morphology lookup). If no one objects I'll look into this option.

**Comment by amir-zeldes** [comment]
OK, take a look at the question mark next to the Coptic input box now - what do you think?

**Comment by ctschroeder** [comment]
This looks fine, though I think will be more prone to user error.

Can you also add one more character? ⳡ as in ⳡⲓⲧⲉ? I came across it the other day.  Crum uses psi (http://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=273) but our lexicon file has ⳡ.  Perhaps @phoenix-mossimo could tell us if there are any other characters we need to add.

**Comment by amir-zeldes** [comment]
I'm happy to add any letters, but our lexicon doesn't seem to have any entries with this characters, see:

https://corpling.uis.georgetown.edu/coptic-dictionary/results.cgi?coptic=.*%E2%B3%A1.*&dialect=any&pos=any&definition=&def_search_type=exact+sequence&lang=any

I do find the khori like this ϧ:  

https://corpling.uis.georgetown.edu/coptic-dictionary/results.cgi?coptic=.*%CF%A7.*&dialect=any&pos=any&definition=&def_search_type=exact+sequence&lang=any

Shall I use capital X for that? I've been trying to follow the Antinoou keyboard mappings (at least as they are under Windows). The whole thing is mainly meant to give users without a Coptic keyboard some way of interacting with the dictionary, so I'm OK with them needing to learn the mapping (which is plainly stated in the table, no?).

**Comment by ctschroeder** [comment]
There is a problem, with the query or a bug in the dictionary, or I can no longer read. Try:

https://corpling.uis.georgetown.edu/coptic-dictionary/entry.cgi?entry=1887&super=786

**Comment by amir-zeldes** [comment]
I'd go with bug. I'll look into this.

**Comment by amir-zeldes** [comment]
̀Seems to be something with the sort order. Where does this letter sort? As in, which letter of the Coptic alphabet does it come after? I can't find it in Crum (he has khori and khai though, so I guess we need khai as well)

**Comment by amir-zeldes** [comment]
OK, the bug should be fixed now. The Antinnou keyboard mapping puts this letter on U (altgr+u). I can do that too, but I still need to know how it sorts.

**Comment by phoenix-mossimo** [comment]
Hi, an interesting idea with mapping. I think there are usability issues though:

- the table creates the impression that it is a regular vitrual keybord (you want to click the charaters). This was my intention any my colleques' at the first glance; 
- to type in the word you start going back and forth with the mouse pointer beetween the text field and a "?" sign. The fact that you can type in with the table shown is kind of counter-intuitive for "mouseover" feature;
- on mobile devices the mapping table is not displayed. As far as I understand "mouseover" is converted to "touch" in 'One Web' approach;
-  in text field the cursor jumps back to the end of the word after I delete the character in any other position.

**Comment by amir-zeldes** [comment]
OK, thanks for the feedback, I'll think how I make this work better.

**Comment by amir-zeldes** [comment]
OK, so I now just put in the same virtual keyboard from ANNIS and I think it looks OK. More importantly, it doesn't really require any explanations so it's more fool-proof. Maybe I was just overthinking this - does this look alright for everyone?

**Comment by phoenix-mossimo** [comment]
Works good. Only on my phone I don't see the characters on the keyboard, although they do appear in the input field (see screenshot). So you decided not to use character mapping? It was an interesting idea. 

![screenshot_2017-06-17-08-10-04-422_com android chrome](https://user-images.githubusercontent.com/15609955/27250676-59926df8-5335-11e7-9313-a8e63c4449b6.png)

**Comment by amir-zeldes** [comment]
Yes, I also thought it wouldn't be a bad idea, but it requires a lot of explanations, and this was faster than jquerying the cursor position to solve the problem when deleting characters. I switched it to the embedded Antinoou font, so you can try it again on your phone. Does it work now?

**Comment by phoenix-mossimo** [comment]
works!
