### ISSUE TITLE
ANNIS requires login

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#200]
**Describe the bug**
When clicking on the "more examples" I am redirected to ANNIS as usual, but a login window pops up

**To Reproduce**
1. Go to any lemna, eg https://coptic-dictionary.org/entry.cgi?tla=C2328
2. Click on 'Search for more examples for the lemma ⲙⲁⲁϫⲉ with any sense (ANNIS search)'
3. See error

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser chrome
 - Version 107.0.5304.91

**Additional context**
![Screenshot_20221104-065153_Chrome](https://user-images.githubusercontent.com/56459751/199901420-d032f90d-1d75-44cb-b264-3d3b0f940b0f.jpg)

**Comment by amir-zeldes** [comment]
Thanks for reporting, should be fixed now!
