### ISSUE TITLE
Bad example sentence for the entry Cat

### ISSUE THREAD

**Issue by mark-yacoub** [KELLIA/dictionary#201]
Word you searched for in the dictionary (in Coptic):

Ⲉⲙⲟⲩ 

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C667

Bad example sentence (insert your example):

ⲡⲉⲓⲣⲱⲙⲉ ⲛⲧⲉⲓⲙⲓⲛⲉ ⲕⲁⲛ ⲉⲣϣⲁⲛⲟⲩϣⲱⲛⲉ ⲉⲓ ⲉϫⲱϥ ⲏ ⲟⲩⲙⲛⲧϩⲏⲕⲉ · ⲏ ⲟⲩⲉⲙⲟⲩ · ϥⲛⲁϭⲱⲧⲡ ⲁⲛ ϩⲏⲧϥ ·
And if there cometh upon such a man who doeth such things sickness, or poverty, or death,
On Penitence and Abstinence, part 2 (urn:cts:copticLit:johnconst.penitence.budge:120-241)

Notes:

There's no cat in the English translation

**Comment by amir-zeldes** [comment]
Thanks for reporting! The erroneous example has been removed.
