### ISSUE TITLE
Ϣⲱⲙⲉ meaning is not unknown 

### ISSUE THREAD

**Issue by mark-yacoub** [KELLIA/dictionary#202]
**Describe the bug**
The meaning of ϣⲱⲙⲉ is reported as unknown but looking at the examples it seems to mean mother in law. 

**To Reproduce**
1. Go to the meaning of ϣⲱⲙⲉ
2. See the translation 

**Expected behavior**
Meaning is Mother in law

**Desktop (please complete the following information):**
 - OS: [Android]
 - Browser [🦆🦆 go]

**Comment by amir-zeldes** [comment]
This particular word is indeed unknown, and listed in Crum here (bottom right):

https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=564a&tla=C5881

However, the word 'mother in law' is incorrectly spelled with an omicron [here](https://coptic-dictionary.org/entry.cgi?tla=C5881). The spelling with omega is standard according to Crum, so I will change it.

**Comment by mark-yacoub** [comment]
Hey, sorry I'm a bit confused. You're saying ϣⲟⲙⲉ should be ϣⲱⲙⲉ but its meaning is unknown.
Are you saying it has 2 meanings, 1 is misspelled and the other is unknown?

**Comment by amir-zeldes** [comment]
>  Are you saying it has 2 meanings, 1 is misspelled and the other is unknown?

Yes, that's right. The unknown word ϣⲱⲙⲉ is at the bottom of the second column (the definition before last) in Crum:

https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=564a&tla=C5881

The word 'mother in law' is under the last entry in the left column, under the head word ϣⲟⲙ (father in law). But the feminine form should indeed have an omega.

**Comment by amir-zeldes** [comment]
Fixed
