### ISSUE TITLE
Bad example sentence for the entry ⲥⲁ

### ISSUE THREAD

**Issue by mark-yacoub** [KELLIA/dictionary#204]
Word you searched for in the dictionary (in Coptic):

Ⲥⲁ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C3271

Bad example sentence (insert your example):

ⲁϥϫⲟⲟⲥ ⲛϭⲓⲟⲩϩⲗⲗⲟ ϫⲉⲉⲣϣⲁⲛⲟⲩⲡⲉⲓⲣⲁⲥⲙⲟⲥ ⲧⲱⲟⲩⲛ ⲉϩⲣⲁⲓ ϩⲓϫⲛⲟⲩⲣⲱⲙⲉ ϣⲁⲣⲉⲛⲉⲑⲗⲓⲯⲓⲥ ⲁϣⲁⲓ ⲛⲁϥ ⲛⲥⲁⲥⲁ ⲛⲓⲙ · ⲧⲁⲣⲉϥⲣⲕⲟⲩⲓ ⲛϩⲏⲧ ⲛϥⲕⲣⲙⲣⲙ ⲻ
An old man said, 'If a temptation arises against someone, the trials multiply for him on all sides so that he becomes cowardly and murmurs.'
Apophthegmata Patrum Sahidic 045 (urn:cts:copticLit:ap.45.monbeg)
ⲁϥϭⲟⲡϥ ⲇⲉ ⲛϭⲓ ⲡϩⲗⲗⲟ ⲁϥϫⲓⲧϥ ⲛⲥⲁⲟⲩⲥⲁ ⲁϥⲧⲁⲁⲥ ⲛⲁϥ ·
The old man grabbed him and took him aside and he gave it to him.
Apophthegmata Patrum Sahidic 031 (urn:cts:copticLit:ap.31.monbeg)
ⲛⲉⲁϥⲣϣⲟⲙⲛⲧ ⲅⲁⲣ ⲛϩⲟⲟⲩ · ⲙⲡϥⲟⲩⲱⲙ · ⲟⲩⲇⲉ ⲙⲡⲉϥⲥⲱ · ⲟⲩⲇⲉ ⲙⲡⲉϥϣⲁϫⲉ ⲛⲙⲙⲁⲛ · ⲟⲩⲇⲉ ⲙⲡϥⲡⲟⲟⲛϥ ⲉⲡⲉⲓⲥⲁ ⲙⲛⲡⲁⲓ · ⲁⲗⲗⲁ ⲉϥⲛⲏϫ ⲡⲉ ⲛⲧϩⲉ ⲛⲛⲉⲧⲙⲟⲟⲩⲧ ϩⲙⲡⲙⲁ ⲛⲧⲛⲟϭ ⲛⲣⲓ ·
Now he passed three days wherein he neither ate nor drank, neither did he speak unto us, nor turn from one side to the other, but he lay stretched out like a dead man in the hall of the large cell.
Life of Pisentius part 3 (urn:cts:copticLit:lives.pisentius.budge:58-84)

Notes:

None of these examples have the meaning of man.

**Comment by amir-zeldes** [comment]
Thanks, will fix. I can find a few genuine ones:
  * urn:cts:copticLit:pstimothy.abbaton.budge:1-21
  * urn:cts:copticLit:ot.sir.coptot:11
  * urn:cts:copticLit:nt.matt.sahidica:12
