### ISSUE TITLE
Bad example sentence for the entry ⲧⲟⲉ

### ISSUE THREAD

**Issue by mark-yacoub** [KELLIA/dictionary#205]
Word you searched for in the dictionary (in Coptic):

Ⲧⲟⲉ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C4066

Bad example sentence (insert your example):

ⲁⲩⲱ ⲁⲥϣⲱⲡⲉ ϩⲛⲧⲙⲉϩ ϥⲧⲟⲉ ⲛⲣⲟⲙⲡⲉ ϩⲓⲇⲁⲣⲓⲟⲥ ⲡⲣⲣⲟ ⲡϣⲁϫⲉ ⲙⲡϫⲟⲉⲓⲥ ⲁϥϣⲱⲡⲉ ϣⲁⲍⲁⲭⲁⲣⲓⲁⲥ ⲛⲥⲟⲩ ϥⲧⲟⲟⲩ ⲙⲡⲙⲉϩ ⲯⲓⲥ ⲛⲉⲃⲟⲧ ⲭⲁⲥⲓⲗⲓⲟⲩ
And it came to pass in the fourth year of Darius the king, that the word of the Lord came to Zacharias on the fourth day of the ninth month, which is Chaseleu.
38_Zechariah_7 (urn:cts:copticLit:ot.zech.coptot:7)

Notes:

It seems that it should mean 4 not share in this context

**Comment by amir-zeldes** [comment]
Thanks for reporting, will fix!
