### ISSUE TITLE
Bad example sentence for the entry ϭⲱⲃⲉ

### ISSUE THREAD

**Issue by mark-yacoub** [KELLIA/dictionary#206]
Word you searched for in the dictionary (in Coptic): ϭⲱⲃⲉ

ϭⲱⲃⲉ 

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C7563

Bad example sentence (insert your example):

(En) | meaning unknown
-- | --
  | (Fr) | sens inconnu
  | (De) | Bedeutung unbekannt

Notes:

The meaning seems to be leaves from the extracted examples. Also in Psalm 1:3

Better examples:

ⲛⲛⲉϥϭⲱⲃⲉⲛⲁⲥⲣⲟϥⲣⲉϥⲁⲛϩⲱⲃⲛⲓⲙⲉⲧϥⲛⲁⲁⲁⲩⲛⲁⲥⲟⲟⲩⲧⲛ

**Comment by amir-zeldes** [comment]
Thanks for reporting! This is not exactly an error, or at least the definition isn't - C7563 is indeed a word of unknown meaning spelled ϭⲱⲃⲉ. The word "leaf" is normally spelled ϭⲱⲱⲃⲉ ([C7560](https://coptic-dictionary.org/entry.cgi?tla=C7560)). I can remove the incorrect examples here, as well as adding your nice example from Psalms as a variant spelling for C7560, but currently that spelling is not considered official in that entry.

@dwerning @simondschweitzer would you be OK adding ϭⲱⲃⲉ as an alternate orthography listed also in C7560? If so I would need to have a TLA form ID assigned to it.

**Comment by simondschweitzer** [comment]
Good idea! Do you want to add this directly to your branch? If so please add the line ``<form xml:id="CF32253"><usg type="geo">S</usg><orth>ϭⲱⲃⲉ</orth></form>`` after the line ``<form xml:id="CF17179"><usg type="geo">S</usg><orth>ϭⲱⲱⲃⲉ</orth></form>``

**Comment by amir-zeldes** [comment]
OK, done, thanks!
