### ISSUE TITLE
Error when clicking on "Search in Annis" button if Scriptorium Annis page is already open. 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#21]
Steps to reproduce : 

1. Click on "Search in Annis" button in "Coptic Dictionary Online"-> Scriptorium Annis page opens up with search results -> OK. 
2. Look up another word in the dictionary, click on "Search in Annis" again, switch to Annis Scriptorium page -> parsing error -> NOK.

**Comment by amir-zeldes** [comment]
Yes, I can reproduce this. Let me look into it.

**Comment by amir-zeldes** [comment]
OK, I think I've got it now
