### ISSUE TITLE
Bad example sentence for the entry ⲥⲉⲧⲏ

### ISSUE THREAD

**Issue by mark-yacoub** [KELLIA/dictionary#212]
Word you searched for in the dictionary (in Coptic):

Ⲥⲉⲧⲏ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C3765

Bad example sentence (insert your example):

Ⲡⲧⲏⲣϥ̄

Notes:

The meaning in both examples is 60

**Comment by amir-zeldes** [comment]
Thanks for reporting - I can't find a legitimate example of the intended word in our sources, so I've just removed these examples. If anyone knows of one, please let me know!
