### ISSUE TITLE
Bad example sentence for the entry <ENTRY>

### ISSUE THREAD

**Issue by mark-yacoub** [KELLIA/dictionary#213]
TLA lemma no. C7723
ϭⲟⲙ

All the examples are wrong

**Comment by amir-zeldes** [comment]
Thanks for reporting - Crum only cites this reading for later chapters of Ezekiel, but the CoptOT text only goes up to chapter 5, so I can't link those examples. Removing the examples for now.

**Comment by mark-yacoub** [comment]
Hey, just curious - how does he refer to Ezekiel if we only have till chapter 5?

**Comment by amir-zeldes** [comment]
There are later sources of the Coptic text which include the entire book, but the CoptOT base text which is available in Coptic Scriptorium, and which is based on the oldest manuscripts, does not cover those portions yet. For more information on the project see:

https://coptot.manuscriptroom.com/
