### ISSUE TITLE
Bad example sentence for the entry ⲟⲩⲱϩⲉ

### ISSUE THREAD

**Issue by LawrenceRafferty** [KELLIA/dictionary#218]
Word you searched for in the dictionary (in Coptic):

ⲟⲩⲱϩⲉ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C5321

Bad example sentence (insert your example):

ⲧⲉⲧⲛⲁϩⲱⲙ ⲉϫⲛⲛϩⲟϥ ⲙⲛⲛⲟⲩⲱϩⲉ ·
Ye shall tread upon serpents and scorpions.
Discourse on Abbaton part 1 ([urn:cts:copticLit:pstimothy.abbaton.budge:1-21](http://data.copticscriptorium.org/urn:cts:copticLit:pstimothy.abbaton.budge:1-21))

Notes:

The example incorrectly refers to [scorpions](https://coptic-dictionary.org/entry.cgi?tla=C5302) instead of fishers.

I guess the bad example is due to the (presumably variant) spelling, which does match [Budge](https://archive.org/details/CopticMartyrdomshighResByEWallisBudgeVol01/page/n305/mode/1up).

Better example:

I like this as a replacement example since it includes relevant context rather than just a bare use of the noun https://annis.copticscriptorium.org/annis/?id=8ea476ba-cf88-4c1d-bd8f-8173466aeb8d
…ⲡⲟⲩⲱϩⲉ ⲙⲉϥⲛⲕⲟⲧⲕ · ⲁⲗⲗⲁ ϣⲁϥϣⲱⲡⲉ ⲉϥⲟ ⲛⲟⲩϣⲏ ⲛⲣⲟⲉⲓⲥ ⲛⲧⲉⲩϣⲏ ⲧⲏⲣⲥ ϣⲁⲛⲧϥϭⲱⲡⲉ ⲛⲟⲩⲙⲏⲏϣⲉ ⲛⲧⲃⲧ
…the fisherman doth not sleep, but keepeth watch the whole night long until he hath caught a multitude of fishes.
On Penitence and Abstinence, part 2 ([urn:cts:copticLit:johnconst.penitence.budge:120-241](https://data.copticscriptorium.org/urn:cts:copticLit:johnconst.penitence.budge:120-241))

urn:cts:copticLit:johnconst.penitence.budge:120-241 chapter 134, verse 6

**Comment by amir-zeldes** [comment]
Thanks for reporting - I've marked it for replacement, it will update once we do the next example generation round (I'm waiting for that spreadsheet to fill up a bit and then we can do an update)
