### ISSUE TITLE
Blank page as search result

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#22]
After the update many queries started to deliver a blank page (query via "Quick search"). Observed with: 
 
ϭⲓⲛⲕⲱ ⲉⲃⲟⲗ
ϫⲓⲛϯⲭⲗⲟⲙ
ⲣⲡⲛⲁ
ⲕⲟⲙϥ
ⲭⲣⲉⲙⲥ
ⲣⲕⲁϩ 

I initially thought it applies to compounds, but  ϫⲓⲛⲭⲱ ⲉⲃⲟⲗ is correct.

**Comment by amir-zeldes** [comment]
OK, thanks for catching this, it should work now. It was a bug affecting hits with only one result. Let us know if you notice any other problems.
