### ISSUE TITLE
Add links to Logeion for Greek words

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#232]
It looks like a lot of people like Logeion for Greek dictionary lookup, we could easily add it next to Perseus. Example link:

https://logeion.uchicago.edu/%CE%B4%CE%AD

(URL suffix is just polytonic Greek utf8 for de)

**Comment by somiyagawa** [comment]
Υεαη, Logeion has 11 sources as far as I know; I often use it, too.

1. LSJ
2. DGE
3. Bailly 2024
4. Grieks Nederlands
5. Pape
6. Cunliffe Homer
7. Slater Pindar
8. Abbott-Smith NT
9. LMPG
10. Autenrieth Homer
11. Middle Liddell

**Comment by amir-zeldes** [comment]
Just implemented and deployed this since it's a simple link (Perseus is also still available). Feedback welcome!
