### ISSUE TITLE
Bad example sentence for the entry ⲕⲃⲟ

### ISSUE THREAD

**Issue by bkrawiec** [KELLIA/dictionary#233]
Word you searched for in the dictionary (in Coptic): 

ⲕⲏⲃ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C1112

Bad example sentence (insert your example):

ϭⲱϣⲧ ϭⲉ ⲱ ⲡⲙⲟⲛⲁⲭⲟⲥ ⲙⲡⲣⲧⲣⲉⲡⲉⲕϩⲁⲡ ϣⲱⲡⲉ ⲉϥⲕⲏⲃ ⲉⲣⲟⲕ ⲛⲅⲁⲥⲭⲩⲙⲟⲛⲏ ⲉⲧⲃⲉⲛⲉⲕⲡⲣⲁⲝⲓⲥ ⲉⲧϩⲟⲟⲩ
Watch carefully, then, O monk, and make not thy judgement to be double upon thee, and thyself to be ashamed of thy evil actions.
The Asceticon of Apa Ephrem part 2 ([urn:cts:copticLit:psephrem.asceticon.budge:24-55](http://data.copticscriptorium.org/urn:cts:copticLit:psephrem.asceticon.budge:24-55))

Notes:

This is an example of the VSTAT of ⲕⲱⲃ, be doubled, not ⲕⲃⲟ, to cool.

**Comment by amir-zeldes** [comment]
Ooh, that's a nasty one because it's impossible to disambiguate without context (ⲕⲏⲃ is VSTAT to both of those verbs). Since this is a manually curated corpus in GD I just fixed it there and it will eventually propagate. Thanks for reporting!
