### ISSUE TITLE
Bad example sentence for the entry <ⲟⲩⲱϫⲉ>

### ISSUE THREAD

**Issue by bkrawiec** [KELLIA/dictionary#235]
Word you searched for in the dictionary (in Coptic): 

ⲟⲩⲱϫⲉ 

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C5344 

Bad example sentence (insert your example):

ⲁⲩⲱ ⲁⲩϫⲓⲧϥ ⲉϥⲟⲩⲟϫ ϣⲁⲡⲉϥⲉⲓⲱⲧ .
And he was taken safely to his father.
Apophthegmata Patrum Sahidic 099: Anonymous N 293 ([urn:cts:copticLit:ap.99.monbeg](http://data.copticscriptorium.org/urn:cts:copticLit:ap.99.monbeg))

ⲛⲧⲟⲕ ⲇⲉ ϣⲁϫⲉ ⲛⲛⲉⲧⲉϣϣⲉ ⲛⲧⲉⲥⲃⲱ ⲉⲧⲟⲩⲟϫ .
But say the things which fit sound doctrine,
56_Titus_2 ([urn:cts:copticLit:nt.titus.sahidica:2](http://data.copticscriptorium.org/urn:cts:copticLit:nt.titus.sahidica:2))

Notes:

In both cases the word ⲟⲩⲟϫ is more likely the VSTAT of ⲟⲩϫⲁⲓ. The second example matches exactly the phrase in the text I am currently annotating and the lemma was tagged as ⲟⲩⲱϫⲉ. 

Better examples:

**Comment by amir-zeldes** [comment]
I fixed the AP example in the source data so that should disappear in the next release. Titus is fully automatically annotated, I'll block it as an example and hope the NLP does better on it the next time we release the NT. Thanks!
