### ISSUE TITLE
Bad example sentence for the entry ⲁⲣⲝ, "bear"

### ISSUE THREAD

**Issue by MMKBE14** [KELLIA/dictionary#238]
Word you searched for in the dictionary (in Coptic):

ⲁⲣⲝ, "bear" 

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C8441

Bad example sentence (insert your example):

ⲛⲧⲉⲥⲁⲣⲝ ⲛⲓⲙ ⲛⲁⲩ ⲉⲡⲉⲟⲟⲩ
and all flesh shall see the salvation of God'
Path: sahidic.ot > 23_Isaiah_40 (tokens 105 - 115)
(https://annis.copticscriptorium.org/annis/?id=911e9eb3-f562-4e3f-a581-729d74a42276)

ⲛⲧⲉⲥⲁⲣⲝ ⲛⲓⲙ ⲁⲓⲥⲑⲁⲛⲉ ϫⲉ
and all flesh shall perceive
Path: sahidic.ot > 23_Isaiah_49 (tokens 1091 - 1101)
https://annis.copticscriptorium.org/annis/?id=5b8dfade-a1ac-4480-87c1-22d67d468360

ⲛⲧⲉⲥⲁⲣⲝ ⲛⲓⲙ ⲉⲓ ⲙⲡⲁⲙⲧⲟ
that all flesh shall come … before me 
Path: sahidic.ot > 23_Isaiah_66 (tokens 1013 - 1023)
https://annis.copticscriptorium.org/annis/?id=da62e665-c2ec-4c76-b6d1-f0bcba405299

ⲛⲧⲉⲥⲁⲣⲝ ⲛⲓⲙ ⲛⲁⲩ ⲉⲡⲉⲩϫⲁⲓ ⲙⲡⲛⲟⲩⲧⲉ
All flesh will see God's salvation 
Path: sahidica.nt > 42_Luke_03 (tokens 186 - 196)
https://annis.copticscriptorium.org/annis/?id=582acb6c-4992-4637-8b2b-a8d39ce7c22e

Notes:

Not correctly segmented, word here is ⲥⲁⲣⲝ, 'flesh'

Better examples:

The remaining examples look ok superficially.

**Comment by amir-zeldes** [comment]
Thanks for reporting - there are more examples so we should be able to replace the bad one, for example one in Pistis Sophia here:

https://annis.copticscriptorium.org/annis/?id=a887bc43-7c79-4c62-8575-739d6bf9bc37

This will get refreshed on our next release.
