### ISSUE TITLE
Drop-down menu "Dialects" 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#24]
Quote from the user: "Sorry for disturbing you a lot, does the dictionary have the Bohairic Dialect?  I tried to write ⲥⲱⲧⲉⲙ (...) it does not give me the meaning, **although I chose the Bohairic dialectic in the dictionary**? any thought? " >

I guess the "Dialects" drop-down creates an impression that we offer dialectal information as well. We do this only for the lemmata which are not attested in Sahidic + a number of words in "Alpha" and "Beta".

**Comment by amir-zeldes** [comment]
Hi @phoenix-mossimo - what exactly did you want me to do about this?

**Comment by phoenix-mossimo** [comment]
I would hide dialects drop-down for now, as we dont offer a proper funtionality behind it, which leads to user frustration (quoted above). 

We could present dialects as a major new feature in one of the upcoming releases - as soon as the integration of Funk is completed.

**Comment by phoenix-mossimo** [comment]
I close that as we got dialects in Greek-Coptic (DDGLC) data. More dialect forms are coming via Funk.
