### ISSUE TITLE
Bad example sentence for the entry ϥⲛⲧ

### ISSUE THREAD

**Issue by MMKBE14** [KELLIA/dictionary#240]
Word you searched for in the dictionary (in Coptic):

ϥⲛⲧ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C6277

Bad example sentence (insert your example):

ⲁⲩⲱ	ϣⲁϥⲛⲧⲥ	ⲉⲃⲟⲗ	ϩⲓⲧⲉϩⲓⲏ
and it leadeth it forth on the way
pistis.sophia > pistis.sophia_book_3_part2 (tokens 4168 - 4178)
https://annis.copticscriptorium.org/annis/?id=b207061d-0340-4f2d-ad96-13a21777d3ca

Notes:

Not the noun ϥⲛⲧ here, but an aorist with the verb eine: ϣⲁ-ϥ-ⲛⲧ-ⲥ

also https://annis.copticscriptorium.org/annis/?id=d2328dcb-a26a-44bd-9be4-157eb43c0590
pistis.sophia > pistis.sophia_book_3_part3 (tokens 3125 - 3135)

Likewise in the OT here
https://annis.copticscriptorium.org/annis/?id=0efba382-4035-4b43-8b01-209971b07918
and here
https://annis.copticscriptorium.org/annis/?id=b695dcfb-bc61-4ddb-9cda-9cef10ae658d
but I reckon you cannot adjust these.

Better examples:

<If you have better examples from Scriptorium corpora, please list them here, ideally with the document_cts_urn, chapter and verse numbers>

**Comment by amir-zeldes** [comment]
Thanks! Will fix Pistis Sophia - that's right about the OT, although we will eventually re-process it and we expect fewer mistakes in each iteration (but not necessarily this one).
