### ISSUE TITLE
Bad example sentence for the entry ⲛ- (ⲁⲛ)

### ISSUE THREAD

**Issue by pmissael** [KELLIA/dictionary#248]
Word you searched for in the dictionary (in Coptic):

ⲛ- (negation)

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C2351

Bad example sentence (insert your example):

All examples

Notes:

The examples shown are of the strings ⲛⲁⲛ, probably because the search query is "norm_group=‎/.*ⲛ(ⲁⲛ).*‎/". It should be: norm=‎"ⲛ‎" _=_ pos=‎"NEG‎"

Better examples:

**ⲛ**ⲅⲛⲁϭⲱⲧⲡ ⲁⲛ ϩⲁ ⲧⲉⲩϩⲏ ⲉⲃⲟⲗ ϫⲉ ⲡϫⲟⲉⲓⲥ ⲡⲉⲕⲛⲟⲩⲧⲉ ϣⲟⲟⲡ ⲛⲉⲙⲁⲕ ⲉⲩⲛⲟϭ ⲡⲉ ⲡⲛⲟⲩⲧⲉ ⲉϥⲧⲁϫⲣⲏⲟⲩ. (Deut 7:21) 05_deuteronomy_7(urn:cts:copticLit:ot.deut.coptot:7)

**Comment by amir-zeldes** [comment]
I see the issue - because of the round brackets, the entry is understood by the example search to be looking for something containing ⲛ+ⲁⲛ, but actually we are only concerned with the ⲛ here. It's easy to find examples, I'll list three manually for the next release. Thanks!
