### ISSUE TITLE
POS category for mpOr

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#25]
@phoenix-mossimo : We're treating ⲙⲡⲱⲣ as an imperative verb form (SC tag `VIMP`), but in the lexicon XML it's `Interjektion`, which may surprise some users moving between the dictionary and ANNIS corpora. Is there any chance this could be changed into an imperative verb in the lexicon?

**Comment by phoenix-mossimo** [comment]
Corrected: 
'''
                <gramGrp>
                    <pos>Vb.</pos>
                    <subc>Imperativ</subc>
                </gramGrp>
'''
