### ISSUE TITLE
Possible duplicate entries for ϯϩⲟ: C4760, C6401

### ISSUE THREAD

**Issue by LawrenceRafferty** [KELLIA/dictionary#250]
Should [C4760](https://coptic-dictionary.org/entry.cgi?tla=C4760) and [C6401](https://coptic-dictionary.org/entry.cgi?tla=C6401) be merged? Cf. the similar glosses and references, and the single headword at [CD 648b](https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=648b&tla=C4760).

If not, what is the distinction?

The redirection entry for ϯϩⲟ on [CD 457a](https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=457a) may be the source of C4760 based on this sequence:
C4759 ϫⲓⲛϣⲧⲉⲙⲑⲓϧⲓ…
C4760 ϯϩⲟ _v_ ϩⲟ.
![image](https://github.com/user-attachments/assets/9f41cfa6-6acd-44d9-a469-fe4f6c7b2cbe)

**Comment by amir-zeldes** [comment]
Looks like a duplicate to me - @dwerning @simondschweitzer can you remove one of them from CCL?

**Comment by simondschweitzer** [comment]
The dataset for C4760 is now deprecated:
```
      <entry change="#deprecated #v1.3" xml:id="C4760">
        <form type="lemma" xml:id="CF11484">
          <usg type="geo">S</usg>
          <orth>ϯϩⲟ</orth>
        </form>
        <form xml:id="CF11485">
          <usg type="geo">S</usg>
          <orth>ϯϩⲟ</orth>
        </form>
        <gramGrp>
          <pos>Vb.</pos>
          <subc>Kompositverb</subc>
        </gramGrp>
        <xr type="cf">
          <ref target="#C4020" type="entry">give, pay, sell</ref>
        </xr>
        <xr type="cf">
          <ref target="#C6398" type="entry">face</ref>
        </xr>
        <sense xml:id="CS5377">
          <cit type="translation">
            <quote xml:lang="de">anflehen</quote>
            <quote xml:lang="en">beseech</quote>
            <quote xml:lang="fr">supplier</quote>
            <bibl>CD 648b; KoptHWb 257; DELC 225b; ChLCS 87a</bibl>
          </cit>
        </sense>
      </entry>
```
