### ISSUE TITLE
Incorrect French and German glosses for C1483 ⲕⲁϣ

### ISSUE THREAD

**Issue by LawrenceRafferty** [KELLIA/dictionary#252]
[C1483](https://coptic-dictionary.org/entry.cgi?tla=C1483) has the following glosses:

| Language | Gloss |
| --- | --- |
| En | reed-bed, plantation |
| Fr | **chilfbeet, Schilfbepflanzung** |
| De | **mit Schilf umgebenm, einzäunen** |

There are two problems:

1. The French gloss **chilfbeet, Schilfbepflanzung** is German text (and is missing the first letter of **Schilfbeet**.)

   - Cf. [C1480](https://coptic-dictionary.org/entry.py?tla=C1480) ⲙⲁ ⲛⲕⲁϣ **parterre de roseaux, plantation de roseaux**.
   - Cherix (V.18.1 p. 20a, V.23.1 p. 14b) has **roselière, jonchaie**. Note it indicates **nm**, though [Crum 130b](https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=130b&tla=C1483) has **nn f**  and KoptHWb 72 has **fem.** (I do not know if Cherix has a typo or if the designation as masculine is contra the others.)
     - Is the mismatch of masculine/feminine the reason this is omitted from the Bibliography for C1483?

2. The German gloss **mit Schilf umgebenm, einzäunen** does not seem to fit this entry. KoptHWb 72 **Schreibrohr, Pfahl, Palisade**, Crum 130b **as paling**, and Cherix **palissade** all seem to indicate this meaning is an unlisted sense of [C1479](https://coptic-dictionary.org/entry.py?tla=C1479). For this entry KoptHWb 72 has **Schilfanpflanzung**.

   - Cf. [C1482](https://coptic-dictionary.org/entry.py?tla=C1482) **mit Schilf umgeben, einzäunen**. For the lemma spelling see https://github.com/KELLIA/dictionary/issues/253.
   - Cf. [C1480](https://coptic-dictionary.org/entry.py?tla=C1480) ⲙⲁ ⲛⲕⲁϣ **Schilfbeet, Schilfbepflanzung**.

**Comment by amir-zeldes** [comment]
Thanks for pointing this out - adding @simondschweitzer @dwerning

**Comment by simondschweitzer** [comment]
Thank you for pointing out the translation errors! C1483 refers to the feminine noun for which KoptHWb 72 gives the meaning “Schilfanpflanzung”, while C1479 is the masculine noun with the meaning “Schilfrohr”. In the next version, C1483 will be:
        <entry xml:id="C1483">
          <form type="lemma" xml:id="CF4390">
            <usg type="geo">S</usg>
            <orth>ⲕⲁϣ</orth>
          </form>
          <form xml:id="CF4391">
            <usg type="geo">S</usg>
            <orth>ⲕⲁϣ</orth>
          </form>
          <gramGrp>
            <pos>Subst.</pos>
            <gen>f.</gen>
          </gramGrp>
          <sense xml:id="CS1728">
            <cit type="translation">
              <quote xml:lang="de">Schilfanpflanzung</quote>
              <quote xml:lang="en">reed-bed, plantation</quote>
              <quote xml:lang="fr">plantation de roseaux</quote>
              <bibl>CD 130b; KoptHWb 72</bibl>
            </cit>
          </sense>
        </entry>

**Comment by simondschweitzer** [comment]
Now with the correct layout ;-)
Thank you for pointing out the translation errors! C1483 refers to the feminine noun for which KoptHWb 72 gives the meaning “Schilfanpflanzung”, while C1479 is the masculine noun with the meaning “Schilfrohr”. In the next version, C1483 will be:
```
        <entry xml:id="C1483">
          <form type="lemma" xml:id="CF4390">
            <usg type="geo">S</usg>
            <orth>ⲕⲁϣ</orth>
          </form>
          <form xml:id="CF4391">
            <usg type="geo">S</usg>
            <orth>ⲕⲁϣ</orth>
          </form>
          <gramGrp>
            <pos>Subst.</pos>
            <gen>f.</gen>
          </gramGrp>
          <sense xml:id="CS1728">
            <cit type="translation">
              <quote xml:lang="de">Schilfanpflanzung</quote>
              <quote xml:lang="en">reed-bed, plantation</quote>
              <quote xml:lang="fr">plantation de roseaux</quote>
              <bibl>CD 130b; KoptHWb 72</bibl>
            </cit>
          </sense>
        </entry>
```
