### ISSUE TITLE
Suspected transcription error in lemma for C1482: ϯ ⲉⲛⲕⲁϣ should be ϯ ⲉⲡⲕⲁϣ

### ISSUE THREAD

**Issue by LawrenceRafferty** [KELLIA/dictionary#253]
[C1482](https://coptic-dictionary.org/entry.py?tla=C1482) has the lemma ϯ ⲉⲛⲕⲁϣ, but I suspect it should be ϯ ⲉⲡⲕⲁϣ (**ⲡ**, not **ⲛ**).

Sometimes in Crum those letters can be hard to distinguish, but the spelling in the examples, as well as the lemma in Cherix, agree with **ⲡ**:

- [CD 130b](https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=130b&tla=C1482) 
![image](https://github.com/user-attachments/assets/e6f99807-a2dc-42d3-8806-222e2801bc1b)

- Cherix (V.18.1 p. 20a, V.23.1 p. 14b)
  ![image](https://github.com/user-attachments/assets/48b7bb30-147a-4fa7-b7ea-23323a14f065) 

Examples of this lemma in the Scriptorium: https://annis.copticscriptorium.org/annis/?id=21f16386-4f64-4bb2-b47f-6bf4caf68b6f

- ϯ ⲙⲡⲙⲁ ⲛⲉⲗⲟⲟⲗⲉ ⲉⲡⲕⲁϣ https://data.copticscriptorium.org/urn:cts:copticLit:pistissophia.1.petermann:84-96
- ⲁⲓⲧⲁⲁϥ ⲉⲡⲕⲁϣ https://data.copticscriptorium.org/urn:cts:copticLit:ot.isa.coptot:5

**Comment by amir-zeldes** [comment]
Thanks, this should be corrected - @dwerning @simondschweitzer please update in CCL!

**Comment by simondschweitzer** [comment]
Thank you! In the next version, the entry will be:

        <entry type="compound" xml:id="C1482">
          <form type="lemma" xml:id="CF4388">
            <usg type="geo">S</usg>
            <orth>ϯ ⲉⲡⲕⲁϣ</orth>
          </form>
          <form xml:id="CF4389">
            <usg type="geo">S</usg>
            <orth>ϯ ⲉⲡⲕⲁϣ</orth>
          </form>
          <gramGrp>
            <pos>Vb.</pos>
            <subc>Kompositverb</subc>
          </gramGrp>
          <xr type="cf">
            <ref target="#C4020" type="entry">give, pay, sell</ref>
          </xr>
          <sense xml:id="CS1727">
            <cit type="translation">
              <quote xml:lang="de">mit Schilf umgeben, einzäunen</quote>
              <quote xml:lang="en">hedge with reeds</quote>
              <quote xml:lang="fr">clôturer</quote>
              <bibl>CD 130b; ChLCS 20</bibl>
            </cit>
          </sense>
        </entry>
