### ISSUE TITLE
Add lemma form type to dictionary reader

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#32]
In the new XML files, one entry form is flagged as type="lemma". There should always be a duplicate of this form - make sure to check for duplicates while harvesting forms with the dictionary reader (i.e. check before doing orths.append(form))

**Comment by phoenix-mossimo** [comment]
Hm, duplicates are also same orths with different dialects, gender, number or parts of speech. Just making sure you don't kick out all duplicates.

**Comment by amir-zeldes** [comment]
That's right - @mjabrams , please check that we're only dealing with the XML element that has the lemma type set

**Comment by amir-zeldes** [comment]
Fixed in https://github.com/KELLIA/dictionary/commit/28899318a9f1ce1f695257b271e1d5587a83657b#diff-9aa40d929bfa223ecbabeeff2915185eR51
