### ISSUE TITLE
Integrate oRef tags

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#33]
Reading:

1. Add a column to the DB entries table called ORef
2. If you find an oRef on top of the orth while reading XML files, this will be the value of ORef
3. Else use the standard search form, which may or may not include spaces

Searching in ANNIS:

For entries with meaningful oRef, generate queries like this:

norm="ϯ" . norm="ⲟⲃ" | morph="ϯ" . morph="ⲟⲃ"

**Comment by phoenix-mossimo** [comment]
Nice function, works over the word boundary - checked with ϭⲙⲡⲟⲩⲟⲉⲓϣ. 
I noticed missing<oRef>ⲣ ⲡ ⲕⲉ-</oRef> in CF3444 and inserted it. Not committed yet.

**Comment by amir-zeldes** [comment]
Glad you like it! There are still a couple of things to do:

  * oRef for multi-morph items (r-hote, etc.)
  * frequency support (currently listed as zero, but could be supported if the lemma harvester is updated)
  * reverse lookup, i.e. putting a link in the ANNIS corpora for things that are known multiword expressions - this is the trickiest one

**Comment by phoenix-mossimo** [comment]
yes, oRef for all multi-morphs would be great.  It is in the plans

**Comment by amir-zeldes** [comment]
That's great - maybe it would be good to give them a distinct separator from multiword-bound groups? We might still want the ANNIS search to check both norm and morph (in case of annotation errors or inconsistencies between ANNIS and the lexicon), but if we have the information about the difference, we may be able to do something with it in the future.

**Comment by phoenix-mossimo** [comment]
Yes, it makes sense to differentiate "regular" compounds from irregular multi-word compounds.

**Comment by amir-zeldes** [comment]
yes, I just need to be able to tell if something is a new 'norm' unit which receives a part of speech (e.g. r-xreia is a verb), versus the multiword unit scenario, which we distinguish by the existence of a determiner (e.g. r|p|meeue, three norms, one bound group). 

There can also be multiword expressions across bound groups and that would be fine for ANNIS, since we do not specify that the sequence of norms must be inside the same bound group, for example:

Same bound group:
lemma="ⲉⲓⲣⲉ" . lemma="ⲡ" . lemma="ⲁⲅⲁⲡⲏ"
https://corpling.uis.georgetown.edu/annis/?id=632518b9-799a-49c0-b9d7-5f9facdc30e2

Multiple bound groups:
lemma="ⲛⲟϭ" . lemma="ⲛ" . lemma="ⲣⲱⲙⲉ"
https://corpling.uis.georgetown.edu/annis/?id=cc61b586-4989-4d97-88f0-58abc8e8daf2

**Comment by phoenix-mossimo** [comment]
> yes, I just need to be able to tell if something is a new 'norm' unit which receives a part of speech (e.g. r-xreia is a verb), versus the multiword unit scenario, which we distinguish by the existence of a determiner (e.g. r|p|meeue, three norms, one bound group).

Are you talking here about using lexicon for NLP service? For Annis query the part of speech and bound group issues are irrelevant I thought - we just send a sequence of norms (ϭⲙ ⲡ ⲟⲩⲟⲉⲓϣ) or lemmata  (ⲛⲟϭ ⲛ ⲣⲱ) and wait for what comes out.

**Comment by amir-zeldes** [comment]
No, you're right, I just mean we could look on purpose for morph="x" . morph="y" or norm="x" . norm="y" based on the construction. Right now, if oRef != orth, then it looks for both just to be safe. We may want to continue that behavior either way, but the information about the distinction could come in handy for some future purpose.
