### ISSUE TITLE
hoou should be VSTAT

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#39]
hoou is listed as a normal verb:

https://corpling.uis.georgetown.edu/coptic-dictionary/entry.cgi?entry=6971&super=2850

Shouldn't it be a 'stative tantum'?

**Comment by phoenix-mossimo** [comment]
Will get a subcategory "Stativ". Derives from *ϩⲟⲩⲁⲓ (KoptHWb 403) .

**Comment by phoenix-mossimo** [comment]
Done
