### ISSUE TITLE
Tooltips for bibliography

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#41]
@ Frank Feder: mir hatte kürzlich ein Ägypter geschrieben, daß er keine Auflösung für die Abkürzungen im Bibliographiefeld, z.B. CD oder CED, im CDO finden kann. Möglicherweise ist das irgendwo erklärt (wir müßten das auf der TLA Website haben, oder?), aber ich konnte bei CDO direkt nichts finden. Das sollte man vielleicht irgendwo leicht auffindbar positionieren.

**Comment by amir-zeldes** [comment]
I'm happy to add these as a tool tip hint if you give me the list of possibilities

**Comment by phoenix-mossimo** [comment]
CD | W. Crum, A Coptic Dictionary, Oxford:                 Clarendon Press, 1939
-- | --
CED | J. Černý, Coptic Etymological                 Dictionary, Cambridge: Cambridge Univ. Press, 1976
KoptHWb | W. Westendorf, Koptisches Handwörterbuch,                 Heidelberg: Winter, 1965 (1977)
DELC | W. Vycichl, Dictionnaire étymologique de                 la langue copte, Leuven: Peeters, 1983
ChLCS | P. Cherix, Lexique Copte (dialecte                 sahidique), Copticherix, 2006-2018
ONB | T. Orlandi, Koptische Papyri                 theologischen Inhalts (Mitteilungen aus der                 Papyrussammlung der Österreichischen Nationalbibliothek                 (Papyrus Erzherzog Rainer) / Neue Serie, 9), Wien:                 Hollinek, 1974
WbGWKDT | H. Förster, Wörterbuch der griechischen                 Wörter in den koptischen dokumentarischen Texten.                 Berlin/Boston: de Gruyter, 2002
Kasser CDC | R. Kasser, Compléments au dictionnaire                 copte de Crum, Kairo: Inst. Français                          d'Archéologie Orientale, 1964
LCG | B. Layton, A Coptic grammar: with a                 chrestomathy and glossary; Sahidic dialect, Wiesbaden:                 Harrassowitz, 2000
Till D | W. Till, Koptische Dialektgrammatik: mit                 Lesestücken und Wörterbuch, München: Beck, 1961
Osing, Pap. Ox. | J. Osing: Der spätägyptische Papyrus BM                 10808, Harrassowitz, Wiesbaden 1976




I guess this is resolved, no? Although I found the tool tip (question mark in a circle) a bit ugly ;-)

**Comment by amir-zeldes** [comment]
Yes, these should be in - feel free to play around with the css and let me know if you find a better option (I was mainly trying to get rid of the underlines, so it looks more different from the links to Crum, which are actual links)

**Comment by phoenix-mossimo** [comment]
Please extend bibliography displayed with Greek source lemmata: 

Bauer: W. Bauer, K. Aland, B. Aland, Griechisch-deutsches Wörterbuch zu den Schriften des Neuen Testaments und der frühchristlichen Literatur, Berlin: de Gruyter, 1988
BDAG: F.W. Danker, W. Bauer, A Greek-English Lexicon of the New Testament and other Early Christian Literature, Chicago/London: University of Chicago Press, 2000
Daris 1991: S. Daris, Il lessico Latino nel Greco d'Egitto (Estudis de Papirologia i Filologia Biblica 2), Barcelona: Ediciones Aldecoa, 1991
Denniston 1959: J.D. Denniston, The Greek Particles, London: Clarendon Press, 1959
du Cange: C. F. du Cange, Glossarium ad scriptores mediae et infimae Graecitatis I-II, Graz: Akademische Druck- und Verlagsanstalt, 1958
Hatch/Redpath 1906: E. Hatch, H.A. Redpath, A concordance to the Septuagint and the other Greek versions of the Old Testament (including the apocryphal books), Supplement, Graz: Akademische Druck- und Verlagsanstalt, 1906
Kontopoulos: N. Kontopoulos, A Lexicon of Modern Greek-English and English-Modern Greek, Smyrna/London: B. Tatikidos, Trübner & Co., 1868
Lampe: G.W.H. Lampe, A patristic Greek lexicon, Oxford: Clarendon Press, 1978
 
LBG: E. Trapp, Lexikon zur byzantinischen Gräzität, besonderes des 9.-12. Jahrhunderts, Philosophisch-historische Klasse, Denkschriften (Veröffentlichungen der Kommission für Byzantinistik 238; VI/1-4) , Wien: Österreichische Akademie der Wissenschaften, 2001
LSJ: H.G. Liddell, R. Scott, H.S. Jones, A Greek-English lexicon, Oxford: Clarendon Press, 1968
LSJ Suppl.: H.G. Liddell, R. Scott, H.S. Jones, E.A. Barber, A Greek-English lexicon/Supplement, Oxford: Clarendon Press, 1968
Muraoka 2009: T. Muraoka, A Greek-English Lexicon of the Septuagint, Louvain/Paris/Walpole: Peeters, 2009
Passow: F. Passow, V.C.F Rost, F. Palm, Handwörterbuch der griechischen Sprache, Leipzig: Vogel, 1841
Preisigke: F. Preisigke, Wörterbuch der griechischen Papyrusurkunden mit Einschluß der griechischen Inschriften, Aufschriften, Ostraka, Mumienschilder usw. aus Ägypten, Berlin: Selbstverlag der Erben, 1925-1931
Sophocles: E.A. Sophocles, Greek Lexicon of the Roman and Byzantine Periods (From B. C. 146 to A. D. 1100. Memorial Edition), Cambridge/Leipzig: Harvard University Press/Harrassowitz, 1914
T. S. Richter 2014b: T.S. Richter, Neue koptische medizinische Rezepte (Zeitschrift für Ägyptische Sprache und Altertumskunde ZÄS 141(2), 154-194), 2014
Till 1951a: W.C. Till, Arzneikunde der Kopten, Berlin: Akademie Verlag, 1951
TLG: L. Berkowitz, K.A. Squitier, Thesaurus Linguae Graecae (Canon of Greek Authors and Works), New York/Oxford: University Press, 1990

**Comment by phoenix-mossimo** [comment]
@amir-zeldes did you see this?

**Comment by amir-zeldes** [comment]
Yes, why do you ask?
