### ISSUE TITLE
The verb ⲥϭⲏⲣ (sqHr)

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#43]
I can't seem to find the verb ⲥϭⲏⲣ "to sail" in CDO. It has an entry on Crum p. 388B - am I not searching right or is there some reason it's excluded? If not, can it be added?

**Comment by phoenix-mossimo** [comment]
Thank you for this bug. It seems that pp 386b-389 were not encoded. Opened #45
