### ISSUE TITLE
lemma for aueis

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#47]
Currently the lemma au is listed as au(e), with parentheses. The dictionary interface filters the parentheses during search, so searching for "aue" finds this entry, however the Scriptorium lemmatizer uses "au" as the lemma, since Crum lists this as the primary form. This form does not correctly link to "aue", since the form "au" is not listed in the CDO.

I think there should be a separate orthographic form "au" next to "aue", so that both will be found in searching - the double form "au(e)" implicitly contains the same information, but is not easily machine readable, and also implies that the citation form might be "aue" (I think it should be "au" based on Crum).

**Comment by phoenix-mossimo** [comment]
Corrected citation form to "au", added non-citation form "au" (with an available CF number), corrected CF953 to "aue": 

      <entry xml:id="C238">
        <form type="lemma" xml:id="CF952">
          <usg type="geo">S</usg>
          <orth>ⲁⲩ</orth>
        </form>
        <form xml:id="CF18173">
          <usg type="geo">S</usg>
          <orth>ⲁⲩ</orth>
        </form>        
        <form xml:id="CF953">
          <usg type="geo">S</usg>
          <orth>ⲁⲩⲉ</orth>
        </form>

I remember the (global) brackets problem, we will have to deal with it separately.
