### ISSUE TITLE
Missing forms of ⲥϩⲃⲏⲏⲧⲉ 'foam'

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#48]
The form ⲥϩⲃⲏⲏⲧⲉ has a number of alternative Sahidic spellings in Crum, e.g. ⲥⲃⲏⲓⲧⲉ (Sahidica Mark 9:20) - it would be nice to include them, see http://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=384

**Comment by phoenix-mossimo** [comment]
Extended with available Crum forms: 

      <entry xml:id="C3971">
        <form type="lemma" xml:id="CF9881">ⲥϩⲃⲏⲏⲧⲉ</form>
        <form xml:id="CF9882"><orth>ⲥϩⲃⲏⲏⲧⲉ</orth><usg type="geo">S</usg></form>
        <form xml:id="CF18174"><orth>ⲥϩⲃⲏⲧⲉ</orth><usg type="geo">S</usg></form>
        <form xml:id="CF18181"><orth>ⲥϩⲃⲉⲉⲧⲉ</orth><usg type="geo">S</usg></form>
        <form xml:id="CF31416"><orth>ⲥϩⲃⲏⲓⲧⲉ</orth><usg type="geo">S</usg></form>
        <form xml:id="CF31417"><orth>ϩⲃⲏⲏⲧⲉ</orth><usg type="geo">S</usg></form>
        <form xml:id="CF31418"><orth>ⲥϩⲃⲏⲧⲉ</orth><usg type="geo">S</usg></form>
        <form xml:id="CF31419"><orth>ⲥⲫⲏⲓϯ</orth><usg type="geo">B</usg></form>
