### ISSUE TITLE
Code/software license type?

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#52]
Is that right?
_GitHub Readme_: "Software released under **Apache 2.0** license"
_Homepage footer_: "Code released under the **MIT** License"

**Comment by amir-zeldes** [comment]
Sorry, this is a misunderstanding - the Bootswatch CSS theme is MIT:

https://github.com/thomaspark/bootswatch/blob/master/LICENSE

Our own dictionary code is Apache. I will clarify this, it's definitely misleading right now.
