### ISSUE TITLE
fixed table width in <table id="related" ...> bad on small devices

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#54]
entry.cgi: senses in the related list reach out of display on the right on small devices

**Comment by dwerning** [comment]
Device: ... admittedly very old ;) ... Galaxy II Plus (480x800)
![Screenshot_2019-05-22-09-33-13](https://user-images.githubusercontent.com/33833393/58155892-1feaa500-7c75-11e9-9f28-eec813e9f01f.png)

**Comment by dwerning** [comment]
maybe it would be useful to make the barely filled 2nd column non-fixed width?

**Comment by phoenix-mossimo** [comment]
We had the same problem with "Search results" display (see #12), which was resolved.

**Comment by dwerning** [comment]
compare resolved issue #12

**Comment by amir-zeldes** [comment]
OK, thanks for reminding me of #12 , it was the same issue. Should be fixed now.
