### ISSUE TITLE
"You searched for ..." string, Coptic not displayed (by delivered font)

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#56]
![Screenshot_2019-05-24-06-44-55](https://user-images.githubusercontent.com/33833393/58303986-b85a6400-7df2-11e9-99a6-8e1dd2756b15.png)

**Comment by amir-zeldes** [comment]
I can't reproduce this, but since Antinoou works in the list below, I'll just use the same styling for the top. Let me know if this doesn't work.
