### ISSUE TITLE
Display notes about status of DDGLC data

### ISSUE THREAD

**Issue by KaJohn-DDGLC** [KELLIA/dictionary#59]
In contrast to the data of the TLA originating form Crum, the DDGLC data is not taken from a finished publication but a work-in-progress. We would like the reader/user of the CDO to be aware of this fact by two notes for DDGLC-entries (entry ID > C8042). 

Please add the following two notes:
- between “Forms:” and “Form & Dial.	TLA form ID & POS ANNIS”: _"Forms given are unnormalized, attested, and checked orthographies in the DDGLC corpus._"
- after Greek lemma reference at the bottom of the entry: "_The material from DDGLC is a work-in-progress, not a finished publication. This release is strictly preliminary._"

**Comment by amir-zeldes** [comment]
I'm happy to add this - can we add both at the bottom though? I think most users just want to see the translations, and having lots of 'small print' at the top is distracting, so I would put all forms of disclaimers and explanations lower down if that's OK.

**Comment by KaJohn-DDGLC** [comment]
That's OK. Thanks.

**Comment by phoenix-mossimo** [comment]
If these messages will be shown with all types of entries, I would explicitly mention "Greek-Coptic forms". "helper.py" seems not to differentiate between Coptic-Greek and Coptic-Egyptian entries.

**Comment by amir-zeldes** [comment]
It should be possible to figure out if an entity is Greek using the grkId field in the DB. Let me have a look.

**Comment by phoenix-mossimo** [comment]
In case you don't harvest "greek_lemma::grl_ID", another indicator is `<bibl>DDGLC</bibl>`

**Comment by KaJohn-DDGLC** [comment]
Or the entry ID which is currently > C8042

**Comment by amir-zeldes** [comment]
Done
