### ISSUE TITLE
Enable search for TLA nos. in "Quick search" and "Search"

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#64]
I suggest to add a new **search field** for "TLA nos." to the search form.
Also, the **quick search** should display the entries if patterns "C"+digits (ideally also "CF"+digits) appear.

**Comment by amir-zeldes** [comment]
Agreed, that sounds nice and doable - however I want to reach a releasable stable state, so can we assign this to the next version?

**Comment by dwerning** [comment]
Agreed.

**Comment by ctschroeder** [comment]
agree this would be helpful. Just found myself telling a colleague to look for a lemma id number.

**Comment by amir-zeldes** [comment]
OK, this should work in quick search now

**Comment by phoenix-mossimo** [comment]
Please add the FORM ID search as well (e.g. CF345). I added the description if ID search to https://github.com/KELLIA/dictionary/blob/master/templates/howto.html but its is not visible online yet. 
Do you know why?

**Comment by amir-zeldes** [comment]
The production instance doesn't auto pull on commits to GitHub, I do it manually to make sure only tested, stable changes make it in. I can update it, but I see you've already listed the 'CF' option, which is not supported yet, so maybe it's better to wait until that's implemented. Is it right that a form ID is always unique to a single XML lemma ID? Or is there ever the possibility of a CF being used inside multiple lemma IDs?

**Comment by phoenix-mossimo** [comment]
> Is it right that a form ID is always unique to a single XML lemma ID? >

Yes

> Or is there ever the possibility of a CF being used inside multiple lemma IDs?>

No, this should never happen. After parenthesis/brackets issue (#30) is resolved we will have CFs also in `<ptr target=CX_XXX>` tag, referencing the obsolete lemmata. This should be irrelevant for the ID search though, which should check the `xml:id` only.

**Comment by amir-zeldes** [comment]
OK, I'll put this on the todo list then

**Comment by amir-zeldes** [comment]
OK, should be working in quick search now in dev, just type `CF72` etc.

**Comment by phoenix-mossimo** [comment]
This one closed but a related issue opened #139.
