### ISSUE TITLE
Provide dialect info to all forms (XML) (v2)

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#66]
With a new tabular layout of the "Entry detail" the (frequently) empty field "Dialect" became prominent. The reason for missing dialect info is that the core lexicon was intended to be Sahidic, only including words from other dialects if they were not attested in Sahidic. Thus explicit encoding of dialect seemed to be superfluous. In the present context of the permanently growing lexicon I think we have to provide dialect information to all forms.

**Comment by phoenix-mossimo** [comment]
The (temporal) solution could be to display "S" whenever the tag `<usg type="geo">` is not found. @amir-zeldes is it doable?

**Comment by amir-zeldes** [comment]
Should be easy to do
