### ISSUE TITLE
Individual senses not displayed

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#68]
In e.g., Entry TLA lemma no. C8062 (ⲁⲅⲅⲉⲗⲟⲥ), sense no. "3" is not displayed. 

![Bildschirmfoto vom 2019-06-11 um 09 59 19](https://user-images.githubusercontent.com/33833393/59256527-7031a300-8c34-11e9-8216-e04406d5661f.png)

**Comment by phoenix-mossimo** [comment]
What a beautiful bug. The reader somehow ignores senses with linebreak, i.e. 
`<quote>to beseech, entreat, beg s.o. to do s.th. (object2: content of entreaty)</quote>` 

is found, but 

`      <quote>to beseech, entreat, beg s.o. on behalf of s.o. to do s.th. (object3: content of
     entreaty)</quote>` 

is not. See for example https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?tla=C10049, where many senses are missing. 

The linebreak is a result of XML pretty-print, which cuts lines of certain length. Can we solve it in CDO or should I change the settings of Oxygen pretty-print? The latter means we will have a new version though.

**Comment by amir-zeldes** [comment]
Oh wow, nice catch. This should be easy to fix, you don't need to do anything in the XML.

**Comment by amir-zeldes** [comment]
OK this is done too.

@ctschroeder @dwerning @phoenix-mossimo please let me know if we are good to go on your end and I can deploy test to the master instance
