### ISSUE TITLE
query string with blanks before/after string gives no results 

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#69]
Query for "ⲣⲱⲙⲉ " or " ⲣⲱⲙⲉ" brings no results. 
=> Cut initial/final whitespaces.

**Comment by phoenix-mossimo** [comment]
Yes, this should apply for "0" or "-1" position in the string only, because white-spaces in compounds are meaningful. See https://github.com/KELLIA/dictionary/issues/65#issuecomment-497859776

**Comment by amir-zeldes** [comment]
Sure, this is just a simple whitespace stripping issue

**Comment by amir-zeldes** [comment]
Done
