### ISSUE TITLE
"ANNIS frequencies" and "Search in Coptic Scriptorium" hits

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#71]
It is unclear (to me) how the data behind the "ANNIS frequencies" icon and the data behind the link to "Search in Coptic Scriptorium" are related. 
E.g., for the form ⲣⲁ (CF3256) in "TLA lemma no. C956 / ⲣⲁ" there ANNIS frequencies says "not found", but there are three (in this case, hoever, false) hits displayed in the "Coptic Criptiorium" link. Is this a bug or what is behind this?

Anyhow, there is no **information on the page** yet that helps the user to understand **what is behind the three icons**. I suggest to add an explanatory page in 2.1.0.

**Comment by amir-zeldes** [comment]
There are several reasons for differences between corpora in ANNIS and the lexicon interface, which are indeed opaque to users and require clarification:

1. The dictionary frequencies are cached, and currently correspond to data from [Scriptorium release 2.6.0](https://github.com/CopticScriptorium/corpora/releases/tag/v2.6.0). They will be updated to 2.7.0 as part of the planned CDO 2.0.0 release. 
2. A search in 'all ANNIS corpora' has some redundancies: the NT is a corpus, but there are also separate, higher quality corpora for Mark and 1 Corinthians which have been manually corrected. When results appear in these texts, an ANNIS search in all corpora will have duplicate results which are filtered out for the CDO frequencies.
3. Similarly, the UD Coptic Treebank corpus has texts from many other corpora, which have been manually analyzed for syntax - these can also produce duplicate results, though this corpus is not usually searched via the CDO->ANNIS link
4. The CDO search is only equivalent to lemma frequencies if the search is actually a lemma search. For items with spaces, for example, the ANNIS link attempts to retrieve bound group matching the item using wildcards, which will lead to more search results (assuming the user would like high recall), not all of which are counted in the frequencies

I definitely think there should be a detailed explanation of frequency functionality (and collocations) in the how-to page, and I plan to add one soon.

**Comment by amir-zeldes** [comment]
Closed via 47e9ba47a34125cc70370b1fd4620b6afcd085a0
