### ISSUE TITLE
Missing sense of hre

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#75]
There is an entry for ϩⲣⲉ 'food':

https://coptic-dictionary.org/entry.cgi?tla=C6780

But not for the sense 'face, upper part'. Can this sense be added? (I'm not sure it's the same lemma etymologically, so maybe a separate lemma?)

**Comment by phoenix-mossimo** [comment]
It is the other way round - form "ϩⲣⲉ" is missing in "ϩⲣⲁⲓ" "upper part". As I see, it is only attested in compounds, e.g. ⲥⲁϩⲣⲉ Crum (698a); ⲣⲡϩⲣⲉ Westendorf 385). I can: 
 
- add a new entry ⲥⲁϩⲣⲉ "upper part" in the superentry of C3263  "ⲥⲁ" and cross-reference it to ϩⲣⲁⲓ (similar to ⲥⲁⲡⲓⲥⲁ) . 
- add a new entry ⲣⲡϩⲣⲉ "be up" in the superentry of C6768 "ϩⲣⲁⲓ". 

Etymologically, "ϩⲣⲁⲓ" "upper part comes from Hry "being above, uppermost" (TLA lemma 108300: http://aaew.bbaw.de/tla/servlet/GetWcnDetails?u=guest&f=0&l=0&wn=108300&db=0) while
ϩⲣⲉ "food" originates from Xr.t "belongings/possessions (i.e. "this which is under" (TLA lemma 123940: http://aaew.bbaw.de/tla/servlet/GetWcnDetails?u=guest&f=0&l=0&wn=123940&db=0). 

The difference between Egyptian "Hry" and "Xry" was eliminated in Sahidic, where ϩⲣⲁⲓ is both "upper" and "lower", but preserved in Akhmimic, which renders X with "ⳉ". (i.e. ϩⲣⲏⲉⲓ "upper" vs. ⳉⲣⲏⲓ "lower").

**Comment by dwerning** [comment]
There is also a _status pronominalis_ form "ϩⲣⲉ=" (various dialects; but not S, which has "ϩⲣⲁ=") mentioned under "ϩⲟ" 'face, ..., surface'  [Westendorf 351] which will be added with further dialects to https://coptic-dictionary.org/entry.cgi?tla=C6398 (TLA lemma no. C6398 (ϩⲟ)).

**Comment by amir-zeldes** [comment]
Thanks for the etymological information, that is interesting! Concretely I had encountered the form @dwerning is talking about, in a text which is ostensibly Sahidic:

ⲙⲡⲣϥⲓ ϩⲣⲁⲕ ⲉϩⲣⲁⲓ
Do not lift your face

It's in Another Epistle Which Apa Ephraim Wrote to a Beloved Disciple, BritMusOriental6783. It could be a dialectal feature, but generally the text reads completely Sahidic to me.

**Comment by phoenix-mossimo** [comment]
Bound forms of "ϩⲟ" 'face" are actually enlisted in the same super entry, e.g.

st. pronominalis: ϩⲓϩⲣⲁ⸗ "on face of", ϫⲓ ϩⲣⲁ⸗ "occupy oneself" 
st. nominalis: ⲉϩⲣⲛ- "toward face of, among", ⲛⲁϩⲣⲛ- "in presence of, before". 

I can certainly mention the bound forms in the entry of "ϩⲟ", but then the same should be done for other possessed nouns ⲣⲟ, ϩⲏⲧ, ⲧⲱⲣⲉ, ϫⲱϫ, ϩⲏ etc. We did not do that due to the time constraints.

**Comment by amir-zeldes** [comment]
I see... I guess the problem for me was being unable to find it using an expression like `ϩⲣ.*`, but if the lemma is properly `ϩⲟ` then that makes sense... If it's attested in the ANNIS corpora and lemmatized correctly, then ϩⲣⲁ would point to ϩⲟ much like ⲕⲏⲧ points to ⲕⲱⲧ, but a wildcard search doesn't bring that up. I will need to think about it some more. Closing for now, thanks!

**Comment by phoenix-mossimo** [comment]
Maybe extend the functionality of the search query `ϩⲣ.*` to find not only `ϩⲣ...`, but also compounds spelled out `ϫⲓ ϩⲣⲁ⸗`?

**Comment by amir-zeldes** [comment]
I'd be cautious of changing the semantics of regex search... To find what you're suggesting, you could do `.*ϩⲣ.*`, or `.* ϩⲣ.*` (with space before hori).
