### ISSUE TITLE
ⲡⲟⲛⲏⲣⲟⲛ contains forms of ⲡⲟⲛⲏⲣⲟⲥ

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#76]
ⲡⲟⲛⲏⲣⲟⲛ (TLA lemma no. C10246) contains forms of ⲡⲟⲛⲏⲣⲟⲥ (TLA lemma no. C10247). 

See http://coptic-dictionary.org/entry.cgi?tla=C10246 and http://coptic-dictionary.org/entry.cgi?tla=C10247

These should be removed.

**Comment by KaJohn-DDGLC** [comment]
Thanks @phoenix-mossimo! Wrongly linked forms like that will be treated in our XML-version v1.1 - soon to come I hope.

**Comment by KaJohn-DDGLC** [comment]
Treated in (upcoming) CCL v1.2

**Comment by KaJohn-DDGLC** [comment]
close #76

**Comment by phoenix-mossimo** [comment]
Thanks. Two ⲡⲟⲛⲏⲣⲟⲥ-forms marked with  `status="deprecated"` and should not be displayed: 
```
          <form xml:id="CF27148" status="deprecated">
               <orth>ⲡⲟⲛⲏⲣⲟⲥ</orth>
               <usg type="geo">S</usg>
            </form>

            <form xml:id="CF27153" status="deprecated">
               <orth>ⲡⲟⲛⲏⲣⲟⲥ</orth>
               <usg type="geo">M</usg>
            </form>
```
