### ISSUE TITLE
ϣⲡⲏⲣⲉ points to noun twice, not the verb

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#78]
Lemma 6006 mentions the feminine noun (https://coptic-dictionary.org/entry.cgi?tla=C6006) and Crum 581a as well as 581b

Lemma 6007 mentions the masculine (!) noun (https://coptic-dictionary.org/entry.cgi?tla=C6007) and Crum 581a as well as 581b

I'd have expected the noun to point to Crum 581a, and the verb to Crum 581b

**Comment by phoenix-mossimo** [comment]
The verb is ⲣϣⲡⲏⲣⲉ (C6009). The fact that noun ϣⲡⲏⲣⲉ is mentioned twice is the constraint of the TLA data model - masculine and feminine should be put in separate entries.

**Comment by m-linssen** [comment]
Thanks Maxim, I stand corrected - my apologies.
ⲣϣⲡⲏⲣⲉ is what the text has, I (among others) mistook it for ⲣ.ϣⲡⲏⲣⲉ
All these lemmas are fine, with C6006 as Subst. f., mostly f. and  C6007 
as Subst. m., mostly f.
