### ISSUE TITLE
ⲛⲟϭⲛⲉϭ & ⲛⲟϭⲛⲟϭ

### ISSUE THREAD

**Issue by ctschroeder** [KELLIA/dictionary#80]
In the online dictionary, the entry for the lemma for ⲛⲟϭⲛⲟϭ does not contain a reference to a common form ⲛⲟϭⲛⲉϭ. In Crum, the lemma is actually ⲛⲟϭⲛⲉϭ, and the online dictionary entry for ⲛⲟϭⲛⲟϭ correctly points the user to the page in Crum for ⲛⲟϭⲛⲉϭ.  However, since the lemma in the CDO is ⲛⲟϭⲛⲟϭ users who look for ⲛⲟϭⲛⲉϭ never find the entry.  Adding to the confusion, ⲛⲟϭⲛⲟϭ is not even listed as a form in Crum.

Can we add the form ⲛⲟϭⲛⲉϭ or change the entry so that ⲛⲟϭⲛⲉϭ is the primary form for the lemma?  Thank you!

**Comment by phoenix-mossimo** [comment]
Hm, true. The correct form is ⲛⲟϭⲛⲉϭ. Corrected C2724 (verb) and C2725 (noun)
