### ISSUE TITLE
ϣⲉ is marked as Subst. instead of Zahlwort

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#82]
100 is marked as a noun, two hundred a.o. as a numeral.
9 is also odd, same issue: https://coptic-dictionary.org/entry.cgi?tla=C2919

It's tough to "do the math" here with automated lemma look-ups ;)

**Comment by amir-zeldes** [comment]
Thanks for reporting - @phoenix-mossimo in the dictionary interface this comes from the XML Subst. classification, they are usually tagged NUM in the corpora. If you guys fix it in XML, it will auto-update on the next revision.

**Comment by phoenix-mossimo** [comment]
Numerals are for Crum gendered nouns and it looks as if their encoding in XML was inconsistent. I have to get all numerals and assign `<pos>Zahlwort</pos>` along with gender information

**Comment by m-linssen** [comment]
Thank you, I ran into thousand and two as well, so best check all indeed

**Comment by m-linssen** [comment]
Thank you Maxim. I just closed this and am now wondering whether I 
should do such a thing... I thought I'd close it from my side only, sorry

**Comment by phoenix-mossimo** [comment]
Let's leave this issue open until I cleaned up the grammatical information in the source XML. 
ϣⲉ (100), ϣⲟ (1000), ⲧⲃⲁ (10000) are interesting as they are always masculine (with some exceptions for ϣⲉ and ϣⲟ) and thus govern the article, even though the noun they modify can be feminine. Therefore, ⲡϣⲟ ⲛ̅ⲣⲟⲙⲡⲉ - the (masc.) 100 (masc.) of year (fem.) = 100 years.

**Comment by phoenix-mossimo** [comment]
Corrected: 
- C5704 (ϣⲉ) from `<pos>Subst.</pos>`to `<pos>Zahlwort</pos>`
- C2919 (ⲯⲓⲥ) from `<pos>Subst.</pos>`to `<pos>Zahlwort</pos>`
- C5731 (ϣⲟ) from `<pos>Subst.</pos>`to `<pos>Zahlwort</pos>`
- C3616 (ⲥⲛⲁⲩ) from `<pos>Subst.</pos>`to `<pos>Zahlwort</pos>`
- C3617 (ⲥⲛⲧⲉ) from `<pos>Subst.</pos>`to `<pos>Zahlwort</pos>`
- C3618 (ⲥⲛⲁⲩ) and C3619 (ⲥⲛⲧⲉ) unchanged as preposed adjectives `<pos>Adj.</pos>`
- C4898 (ⲙⲛⲧⲟⲩⲉ) from `<pos>Subst.</pos>`to `<pos>Zahlwort</pos>`
- C7436 (ϫⲟⲩⲱⲧ)  from `<pos>Subst.</pos>`to `<pos>Zahlwort</pos>`
