### ISSUE TITLE
"ϩⲓ- " and ⲟⲩⲟⲛ as Vb.

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#83]
Cosmetic perhaps but not binary correct: lemma C6389, ϩⲓ-, is followed by a space in the XML. My search for it failed (I've converted the XML to Excel, and "Match entire cell contents" then doesn't compute) as a result

A stranger case is the fact that ⲟⲩⲟⲛ (Crum 481) isn't present as a verb, yet only as a noun. ⲟⲩⲛ- is present, C5038, as well as ⲟⲩⲛⲧⲉ-, C5039, yet the first lemma (B) in Crum isn't

**Comment by amir-zeldes** [comment]
I can find 6389 in the interface without space. Whitespace in XML is in many contexts meaningless, so this is not really a bug, just a problem for Excel. I would strip values before converting to another format.

About ouon as a strong verb (which I think is very rare?) I'll defer to @phoenix-mossimo - I think in our tagging scheme it would be `EXIST`, since syntactically it's not a verb in the sense of ⲥⲱⲧⲙ etc. For the negative mmon, we usually interpret it as a particle "no", and do not use it as part of the same lemma as the existential negator, although historically this might be justified.

**Comment by m-linssen** [comment]
Hi Amir,

I'll elaborate on my background a bit.
I am translating the gospel of Thomas, and have virtually no knowledge 
of Coptic Greek - although I do have experience with a few other languages.
I have lemmatised all of it and am going through it bit by bit, 
assigning the proper function and meaning to each lemma.
I am assuming that Crum is leading although that is just an assumption, 
and for OYON it starts with the Boharic although the text (a mixture of 
largely S and A2) has ⲟⲩⲛ̄ in logion 16.
Perhaps it is a good idea that I run my findings by any of you by email 
before submitting them in github? I will gladly follow your lead there!

On the other issue, I incidentally have to set things straight about 
whitespace in XML: whitespace in XML is only meaningless outside of tags 
and their content.
An interface content should never be touched, unless explicitly agreed 
upon. The whiteSpace constraint might help in the latter case. In the 
case of XSLT translations the default setting also is to preserve 
whitespace - both of which are for very good reasons.
My background on that is professional, 
https://www.linkedin.com/in/martijnlinssen/ may provide some information 
on that

So, with regards to submitting issues to KELLIA / github, please advise 
- this is a one-time only project for me

Regards,

Martijn Linssen

**Comment by amir-zeldes** [comment]
Hi Martijn,

I'm not sure what you mean by Coptic Greek, but if you're working with Bohairic I should point out that headwords that have a Sahidic form generally use that as the entry (words with no Sahidic forms sometimes do have a Bohairic head word as the lemma). Historically ouon and mmon were verbs in Ancient Egyptian, but synchronically the independent forms do not follow the paradigm of historical infinitives (sOtm), or suffixally conjugated 'verboids' in Layton's terminology (nanou=f etc.), so they are really a sui generis. Generally we've been tagging both existential and possessive forms as `EXIST` to make these easily findable, and distinguish them from Coptic verbs proper.

As for XML, I did say "meaningless in many contexts", and in the context of TEI XML, which the dictionary uses, normalization in element content (whitespace trimming, as well as collapsing, i.e. `s/\s+/ /`) is actually normative, see:

https://wiki.tei-c.org/index.php/XML_Whitespace

**Comment by m-linssen** [comment]
Hi Amir, thanks for the explanation; I just expected Crum to be leading.
I have trimmed all the lemma in my version of KELLIA, and would advice KELLIA to do the same in the light of data consistency

Feel free to close this ticket, my problem has been solved

**Comment by phoenix-mossimo** [comment]
- ⲟⲩⲟⲛ is attested in absolute form in Bohairic only, it was not encoded and will come with Funk data. 

- Stripping white space in the source XML seems to be practical to the users, so I will do it #85.
