### ISSUE TITLE
ⲭⲣⲉⲓⲁ: Subst. and Vb. swapped

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#84]
C10982 is tagged as Vb. but its translations are all nouns; C10983 is tagged as Subst. yet its translations are verbs.
Which one do I get? I think it would suffice to swap the top part with "Form | Dial. | Form ID | POS | Attestation" etc - that should include the Scriptorium tag

**Comment by phoenix-mossimo** [comment]
@KaJohn-DDGLC  - can you take care of this?

**Comment by KaJohn-DDGLC** [comment]
Changed in (upcoming) CCL v1.2

**Comment by phoenix-mossimo** [comment]
C10982 was corrected to "Subst." -> OK
C10983 still has "Subst." -> should be "Vb."  . I changed it to "Vb." in your data. @KaJohn-DDGLC Is this OK?
