### ISSUE TITLE
ϩⲁ-, contains a comma

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#86]
ϩⲁ-,

https://coptic-dictionary.org/entry.cgi?tla=C6328

contains a comma at the end.
I have checked all other entries as a result, and this is the only one

**Comment by phoenix-mossimo** [comment]
Its a typo. Will be corrected, thanks.

**Comment by phoenix-mossimo** [comment]
Corrected with "new_A_3_1.xml"
