### ISSUE TITLE
Second meaning of ϩϫⲟⲡϫⲡ

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#87]
I haven't run into this yet, I think.
Crum 743a has ϩϫⲟⲡϫⲡ, intransitive: feel, grope.
Thomas logion 37 uses it as transitive, but I can't find the meaning of tread that Crum attirbutes to it in that case. The Crum dictionary has intransitive for both, and now I find myself very conflicted: why does that get a separate entry in Crum? It seems to be a special case for A2 only

Please advice

**Comment by phoenix-mossimo** [comment]
> The Crum dictionary has intransitive for both, and now I find myself very conflicted: why does that get a separate entry in Crum?

Maybe because the first meaning ("grope") is associated with blindness, the second ("tread") is not? Also, according to Crum only the second can be used intransitively.

**Comment by m-linssen** [comment]
That was an irrelevant question by me LOL

The issue is that the CD doesn't have the transitive meaning, only the intransitive one.
So, pop quiz: how would someone translate that specific part of Thomas logion 37 while using KELLIA?

**Comment by phoenix-mossimo** [comment]
Extended with a Akhmimic spelling and another meaning oin three languages: 
`<form><orth>ϫⲁⲡϫⲡ</orth><usg type="geo">A</usg></form>`
`<form type="inflected"><orth>ϫⲉⲡϫⲱⲡ⸗</orth><usg type="geo">A</usg></form>`

`<quote>betasten, umhertappen [blind]; (be)treten, trampeln </quote>`
`<quote>grope, feel [blind]; tread</quote>`
`<quote>tâter, fouler [aveugle]; tâtonner</quote>`

Considering the translation please consult the Coptic Scriptorium team.
