### ISSUE TITLE
ⲥ︤ⲧ︦ⲣ︦ⲟ︦ⲥ︥ - superlinear strokes (only) in TLA lemma no. C10535 < and more

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#88]
To my surprise, when I couldn't locate a word, the reason for that was the presence of superlinear strokes. That's a first.
I looked at the lemma in question, and it turns out it comes in dozens: https://coptic-dictionary.org/entry.cgi?tla=C10535

I have fixed my version of the dictionary, but I do wonder why suddenly I find superlinear strokes.
And I also do wonder what the state of the Coptic dictionary will be, around the time that I publish my translation. I'm aiming at Q2 2020 for a first draft with just the translation. I will point to KELLIA for each lemma, but I'd prefer the lemma pointed at to be binary identical to the lemma pointed from...

A word to the wise: I know this is a gigantic project, and I really do appreciate KELLIA enormously. But there comes a time when a product should be considered finished enough for future additions, and that point usually is when and where a full sanity check takes place.
Check each lemma, check each comment (for consistency, language, e.g. English or German, but not both), check for spaces, commas, superlinear strokes, and so on. Cleanse your dictionary, make the final product final. Polish it, make it shine

And then comes step 2: do we say the same things in the same manner?
For instance, do we have only Zahlwort, or do we use gender for those too? When, and why?
Or for instance, why do we sometimes use abbreviations (Pron., Vb.) and why is it that sometimes we don't (Possessivartikel).
And is it useful to include question marks with translated words, as e.g. in: fortress (?)
Do we use commas or semicolons to separate words, as e.g. in:

mount, go up
mount up; ascend (in years)

A few last ones: 
abbess   ("Mother")
netherworld,   "hades", hell
capital (of money),   total, poll tax
lentil(s)
belonging(s),   chattel(s), provisions
branch of date-palm   (as a writing tool = "lanceola scriptoris")
ox; cow
loosen, untie (of   chains, cords etc.)
a bird (named in   magical text with hawk and pelican)

Consistency is what's it all about: make your product perfect. Take a break, take a pause: no more building, no more adding, no more. Stop everything, and perfect the product. Agree on everything, make rules, so that new additions don't add old pains and inconsistencies

Any product can be compared with biology: every product is a human being, following the same lifecycle from birth to death through infancy, childhood, adolescence and maturity.

When I look at KELLIA, I see an adolescent. Please make it mature before continuing

**Comment by phoenix-mossimo** [comment]
1) 
> To my surprise, when I couldn't locate a word, the reason for that was the presence of superlinear strokes. 

Removed existing supralinear strokes in Egyptian-Coptic lexicon: 

C614: 	ⲉ̅ -> ⲉ
C1536: 	ⲗ̅ -> ⲗ
C3260:	ⲥ̅ -> ⲥ

New bug opened for the fact that words with supralinear strokes (in the Greek-Coptic lexicon) are not searchable: #102 

2) 
>For instance, do we have only Zahlwort, or do we use gender for those too? When, and why?

Will be checked with  #82

3)
> Or for instance, why do we sometimes use abbreviations (Pron., Vb.) and why is it that sometimes we don't (Possessivartikel).

These were the conventions picked up by the encoders, we can change them but for now its a minor issue. 

4)
> Do we use commas or semicolons to separate words, as e.g. in: mount, go up  - mount up; ascend (in years)

Created a new issue #102

4)
> And is it useful to include question marks with translated words, as e.g. in: fortress (?). A few last ones:

The following convention will be used in translations: 
- squared brackets `[]` are used for explaining the meaning
- round brackets `()` are used for morphological variants:  

fortress (?) -> fortress [?]
abbess ("Mother") -> abbess ["mother"]
netherworld, "hades", hell -> netherworld, hades, hell
capital (of money), total, poll tax -> capital of money, total, poll tax
lentil(s) -> lentil [so in Crum]
belonging(s), chattel(s), provisions -> belonging(s), chattel(s), provisions [unchanged, so in Crum]
branch of date-palm (as a writing tool = "lanceola scriptoris") -> branch of date-palm [as a writing tool = "lanceola scriptoris"]
ox; cow -> [unchanged, see new issue #102 ]
loosen, untie (of chains, cords etc.) -> loosen, untie [of chains, cords etc.]
a bird (named in magical text with hawk and pelican) -> a bird [named in magical text with hawk and pelican]
