### ISSUE TITLE
ⲣⲉϥϯϩⲁⲡ translation contains epsilon

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#89]
https://coptic-dictionary.org/entry.cgi?tla=C6736 has judge as translation: the e actually is an ⲉ

**Comment by phoenix-mossimo** [comment]
Thanks, this is a typo. Will be corrected.

**Comment by phoenix-mossimo** [comment]
Corrected with "new_A_3_1.xml"
