### ISSUE TITLE
Compound entries do not match ANNIS tokenization

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#9]
Working on the frequencies functionality in the lexicon makes it important to have parity between the lexicon and the corpora in the ANNIS interface. Currently, verbal compounds (`Kompositverb` entries) like rhote are spelled with a space in the lexicon (e.g. "r hote" is a subentry of "eire"). 

This prevents proper link up in both directions: in ANNIS, clicking on the word r-hote does not find this entry, and in the lexicon, clicking on the ANNIS search button doesn't find anything. 

@phoenix-mossimo: Could you remove the spaces in the relevant entries? And send us an updated version of the XML files? Or if the licensing issue is cleared up, just add the updated XML files to the utils/ folder? Thanks!

**Comment by phoenix-mossimo** [comment]
yes, working on it

**Comment by phoenix-mossimo** [comment]
closed
