### ISSUE TITLE
ⲁⲙⲁϩⲧⲉ intr. and tr.? Odd / completely absent entries

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#90]
When you just look up ⲁⲙⲁϩⲧⲉ there are two entries displayed:

ⲁⲙⲁϩⲧⲉ 1. prevail, rule, be in possession, valid, lay hold on
            2. grasp, embrace, possess, restrict, detain
ⲁⲙⲁϩⲧⲉ power, possession

One for the verb, one for the noun. When clicking on the verb, https://coptic-dictionary.org/entry.cgi?tla=C110 is shown which basically has no translation at all, and only a reference to ⲁⲙⲟⲛⲓ

When clicking ⲁⲙⲟⲛⲓ then the following is shown: https://coptic-dictionary.org/entry.cgi?tla=C91

2. | (En) | prevail, be in possession, be strong
    | (Fr) | prévaloir, être en possession de, être fort
    | (De) | sich durchsetzen, besitzen, stark sein

Where is the ⲁⲙⲁϩⲧⲉ 1. and 2., and why does ⲁⲙⲟⲛⲓ have a 2. but not a 1.? And where is the translation of ⲁⲙⲁϩⲧⲉ itself? I'm looking for "grasp", working on logion 65 of Thomas at the moment

Please advice, I'm aiming at releasing a preliminary draft end of January. Thanks

**Comment by phoenix-mossimo** [comment]
As far as I understand this is produced by the line break in <ref type="Greek"> within <sense>, which is a result of XML pretty print. @amir-zeldes can you take care of this? I can also extend the line length in pretty print settings, but this is not a nice solution.

**Comment by amir-zeldes** [comment]
OK, fixed in 7e42179 for the reader script and deployed in production. I'll wait with pushing a new DB until we make a master release, since I don't want to spam the repo deltas with binary files.
