### ISSUE TITLE
Circular reference for https://coptic-dictionary.org/results.cgi?coptic=ⲙⲡ

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#91]
https://coptic-dictionary.org/results.cgi?coptic=ⲙⲡ points to two lemma:

ⲙⲡⲉ | (for ⲙⲡ/ANEGPST)
ⲙⲡ | (for ⲙⲡ/V)

The top one works fine, the bottom one points to... this very page

**Comment by amir-zeldes** [comment]
Thanks for reporting, fixed in lemma source files and deployed.
