### ISSUE TITLE
ϣⲱⲧⲉ (flour / dough) is male, not female

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#92]
ϣⲱⲧⲉ leads to to lemmas:

https://coptic-dictionary.org/entry.cgi?tla=C6101

ϣⲱⲧⲉ | S | CF14207 | Subst. f.
(En) | well, cistern, pit

https://coptic-dictionary.org/entry.cgi?tla=C6102

ϣⲱⲧⲉ | S | CF14209 | Subst. f.
(En) | flour, dough

The second one is male, not female

**Comment by phoenix-mossimo** [comment]
Thanks, will be corrected

**Comment by phoenix-mossimo** [comment]
corrected
