### ISSUE TITLE
ϣⲱⲗⲙ - split across 5 lemmas

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#93]
I think there's something amiss here, please look up

https://coptic-dictionary.org/results.cgi?quick_search=ϣⲱⲗⲙ

I would have at least expected the Sahidic verb to be contained in one place. It is an odd one nonetheless. 3 verbs two nouns

**Comment by phoenix-mossimo** [comment]
Can you be more specific specific about the problem? Spelling ϣⲱⲗⲙ renders five lemmata:

1) Verb "to smell" - https://coptic-dictionary.org/entry.cgi?tla=C5826
2) Noun "a (sense of) smell" - https://coptic-dictionary.org/entry.cgi?tla=C5827
3) Verb "meaning unknown" - https://coptic-dictionary.org/entry.cgi?tla=C5831
4) Noun "meaning unknown" - https://coptic-dictionary.org/entry.cgi?tla=C5830
5) Verb "to draw forth" - https://coptic-dictionary.org/entry.cgi?tla=C5833

**Comment by m-linssen** [comment]
I'd expect the Sahidic verb with two meanings to be just one verb with two meanings, in stead of 2 separate lemmas. But if you think it's fine this way, then such is the case of course

**Comment by phoenix-mossimo** [comment]
You are rights that lemma can contain multiple meanings. But in this particular case Crum puts 1) and 3) into separate entries, and the encoders were just following his convention.
