### ISSUE TITLE
Microsoft autocorrect en dashes in lemmas

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#95]
One of the worst issues when it comes to data integrity: incorporating Microsoft dashes caused by autocorrect. Compare the two below examples:

ϩⲓϫⲛ–
ϩⲓϫⲛ-

Even with the bare eye one can distinguish between the two different kinds of dash.
Microsoft suffers from their own problem, fortunately: https://devblogs.microsoft.com/powershell/em-dash-en-dash-dash-dash-dash/

Basically, all the self-created code extensions that can be handed out by Microsoft Autocorrect should be disabled, but it's the dashes (and double / single quotes) that cause most problems.

Please cleanse every dictionary of these as they'll create issues for binary lookups but most certainly cause severe problems cross-platforms as these are Microsoft-specific codepage entries not supported in most other codepages.
I have found 12 lemmas with the en dash:

ϫⲟⲟⲩ (ⲛⲥⲁ–)
ⲛϫⲓⲟⲩⲉ (ⲉ–)
ϫⲉϥ–
ⲉϫⲛ–
ⲣ ⲉϫⲛ–
ϩⲁϫⲛ–
ⲣ ϩⲁϫⲱ=
ϩⲓϫⲛ–
ⲡⲉⲧϩⲓϫⲛ–
(ⲉⲃⲟⲗ) ϩⲓϫⲛ–
ⲣ ϩⲓϫⲛ–
ϭⲓⲛ–
ϭⲁⲛⲛⲁ–

Similarly, there are two kinds of double hyphens that you use:

ϭⲙⲕ=
ⲙⲙⲟ⸗

I must insist on stressing the enormous importance (sic) of using one and only one, and the most basic one, of every character, and to avoid at all cost the use of Microsoft-specific code page entries

Please address these issues, discuss them, make rules for them, and enhance them by creating simple scripts that check for illegal characters. Your data must be absolutely perfect and consistent at the source, and stay that way. No leading or trailing spaces, no double spaces in between, no illegal characters that cross issues cross-platforms due to codepage incompatibility, and certainly no more than one instance for every single character

Never rely on the eye, it is a very weak and subjective instrument. And never rely on humans for complying always, under every circumstance, with each and every rule. We all have our bad days

Don't go developing fancy input-checks for data entry, that is a very costly and impossible to maintain method. Simply devise a simple script that you run at least once a day, or event-driven, on the data level, at the source. I'd be glad to help out free of charge, my knowledge of programming languages is vast, and easily a dozen times greater than my knowledge of human languages

**Comment by phoenix-mossimo** [comment]
Thanks for catching the n-dash problem. All dashes in the orthographic forms have to be exchanged with a "single hyphen" (U+2010) for status nominalis and a "double oblique hyphen" (U+2E17) for status pronominalis. See #85.

**Comment by phoenix-mossimo** [comment]
Exchanged n-dash ("–") with single hyphen ("‐"), exchanged double hyphen ("=") with double oblique hyphen "⸗" as follows: 


| Form ID | Location | Form WAS | Form IS |
| --- |--- |--- |--------- |
| **N-Dash** |--- |--- |--------- |
| CF16904 | form | ϫⲟⲟⲩ (ⲛⲥⲁ–) | ϫⲟⲟⲩ (ⲛⲥⲁ-)|
| CF16905 | form | ϫⲟⲟⲩ (ⲛⲥⲁ–) | ϫⲟⲟⲩ (ⲛⲥⲁ-)|
| CF16916 | form | ⲛϫⲓⲟⲩⲉ (ⲉ–) | ⲛϫⲓⲟⲩⲉ (ⲉ-)|
| CF16917 | form | ⲛϫⲓⲟⲩⲉ (ⲉ–) | ⲛϫⲓⲟⲩⲉ (ⲉ-)|
| CF16958 | form | ϫⲉϥ– |ϫⲉϥ-|
| CF16959 | form | ϫⲉϥ– |ϫⲉϥ-|
| CF17066 | form | ⲉϫⲛ– |ⲉϫⲛ-|
| CF17067 | form | ⲉϫⲛ– |ⲉϫⲛ-|
| CF17068 | form | ⲣ ⲉϫⲛ– |ⲣ ⲉϫⲛ-|
| CF17069 | form | ⲣ ⲉϫⲛ– |ⲣ ⲉϫⲛ-|
| CF17070 | form | ϩⲁϫⲛ– |ϩⲁϫⲛ-|
| CF17071 | form | ϩⲁϫⲛ– |ϩⲁϫⲛ-|
| CF17074 | form | ϩⲓϫⲛ– |ϩⲓϫⲛ-|
| CF17075 | form | ϩⲓϫⲛ– |ϩⲓϫⲛ-|
| CF17076 | form | ⲡⲉⲧϩⲓϫⲛ– |ⲡⲉⲧϩⲓϫⲛ-|
| CF17077 | form | ⲡⲉⲧϩⲓϫⲛ– |ⲡⲉⲧϩⲓϫⲛ-|
| CF17078 | form | ⲉⲃⲟⲗ ϩⲓϫⲛ– |ⲉⲃⲟⲗ ϩⲓϫⲛ-|
| CF17079 | form | ⲉⲃⲟⲗ ϩⲓϫⲛ– |ⲉⲃⲟⲗ ϩⲓϫⲛ-|
| CF17080 | form | ⲣ ϩⲓϫⲛ– |ⲣ ϩⲓϫⲛ-|
| CF17081 | form | ⲣ ϩⲓϫⲛ– |ⲣ ϩⲓϫⲛ-|
| CF17556 | form | ϭⲓⲛ– |ϭⲓⲛ-|
| CF17557 | form | ϭⲓⲛ– |ϭⲓⲛ-|
| CF17608 | orth | ϭⲁⲛⲛⲁ– |ϭⲁⲛⲛⲁ-|
| CF17609 | orth | ϭⲁⲛⲛⲁ– |ϭⲁⲛⲛⲁ-|


| Form ID | Location | Form WAS | Form IS |
| --- |--- |--- |--------- |
| **Double hyphen** |--- |--- |--------- |
| CF16251 | orth | ϫⲱ= | ϫⲱ⸗|
| CF16252 | orth | ϫⲱ= | ϫⲱ⸗|
| CF16259 | form | ⲁⲧϫⲱⲱⲃ= |ⲁⲧϫⲱⲱⲃ⸗|
| CF16260 | form | ⲁⲧϫⲱⲱⲃ= |ⲁⲧϫⲱⲱⲃ⸗|
| CF16424 | form | ϫⲗⲁⲗⲱ= |ϫⲗⲁⲗⲱ⸗|
| CF16425 | form | ϫⲗⲁⲗⲱ= |ϫⲗⲁⲗⲱ⸗|
| CF16538 | form | ϫⲛⲁ= |ϫⲛⲁ⸗|
| CF16539 | form | ϫⲛⲁ= |ϫⲛⲁ⸗|
| CF16540 | form | ϫⲛⲁ= |ϫⲛⲁ⸗|
| CF16541 | form | ϫⲛⲁ= |ϫⲛⲁ⸗|
| CF16760 | orth | ϫⲁⲣⲕ= |ϫⲁⲣⲕ⸗|
| CF16761 | orth | ϫⲁⲣⲕ= |ϫⲁⲣⲕ⸗|
| CF16940 | form | ϫⲟⲟⲩϩ= (ⲉⲃⲟⲗ) |ϫⲟⲟⲩϩ⸗ (ⲉⲃⲟⲗ)|
| CF16941 | form | ϫⲟⲟⲩϩ= (ⲉⲃⲟⲗ) |ϫⲟⲟⲩϩ⸗ (ⲉⲃⲟⲗ)|
| CF17064 | form | ⲛⲥⲁϫⲱ= |ⲛⲥⲁϫⲱ⸗|
| CF17065 | form | ⲛⲥⲁϫⲱ= |ⲛⲥⲁϫⲱ⸗|
| CF17072 | form | ⲣ ϩⲁϫⲱ= |ⲣ ϩⲁϫⲱ⸗|
| CF17073 | form | ⲣ ϩⲁϫⲱ= |ⲣ ϩⲁϫⲱ⸗|
| CF17218 | form | ϭⲃϭⲱⲃ= |ϭⲃϭⲱⲃ⸗|
| CF17219 | form | ϭⲃϭⲱⲃ= |ϭⲃϭⲱⲃ⸗|
| CF17494 | form | ⲟⲩⲛϭⲟⲙ (ⲙⲙⲟ=) |ⲟⲩⲛϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17495 | form | ⲟⲩⲛϭⲟⲙ (ⲙⲙⲟ=) |ⲟⲩⲛϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17496 | form | ⲟⲩⲛϣϭⲟⲙ (ⲙⲙⲟ=) |ⲟⲩⲛϣϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17497 | form | ⲟⲩⲛϣϭⲟⲙ (ⲙⲙⲟ=) |ⲟⲩⲛϣϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17498 | form | ⲙⲛϭⲟⲙ (ⲙⲙⲟ=) | ⲙⲛϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17499 | form | ⲙⲛϭⲟⲙ (ⲙⲙⲟ=) |ⲙⲛϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17500 | form | ⲙⲙⲛϣϭⲟⲙ (ⲙⲙⲟ=) |ⲙⲙⲛϣϭⲟⲙ (ⲙⲙⲟ⸗)|
| no | form | ⲙⲙⲛϣϭⲟⲙ (ⲙⲙⲟ=) |ⲙⲙⲛϣϭⲟⲙ (ⲙⲙⲟ⸗)|
| no | form | ⲙⲛϣϭⲟⲙ (ⲙⲙⲟ=) |ⲙⲛϣϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17501 | form | ⲙ(ⲙ)ⲛϣϭⲟⲙ (ⲙⲙⲟ=) |ⲙ(ⲙ)ⲛϣϭⲟⲙ (ⲙⲙⲟ⸗)|
| CF17536 | form | ϭⲙⲕ= |ϭⲙⲕ⸗|
| CF17537 | form | ϭⲙⲕ= |ϭⲙⲕ⸗|
| CF17604 | orth | ϭⲛⲟⲛ ⲛϫⲱ= |ϭⲛⲟⲛ ⲛϫⲱ⸗|
| CF17605 | orth | ϭⲛⲟⲛ ⲛϫⲱ= |ϭⲛⲟⲛ ⲛϫⲱ⸗|
| CF17766 | orth | ϭⲓⲣⲁ= |ϭⲓⲣⲁ⸗|
| CF17767 | orth | ϭⲓⲣⲁ= |ϭⲓⲣⲁ⸗|
| CF17822 | form | ϭⲟⲣϥ= |ϭⲟⲣϥ⸗|
| CF17823 | form | ϭⲟⲣϥ= |ϭⲟⲣϥ⸗|
| CF17941 | form | ϭⲱⲧⲡ (ϩⲁⲧϩⲏ=) |ϭⲱⲧⲡ (ϩⲁⲧϩⲏ⸗)|
| CF17942 | form | ϭⲱⲧⲡ (ϩⲁⲧϩⲏ=) |ϭⲱⲧⲡ (ϩⲁⲧϩⲏ⸗)|
