### ISSUE TITLE
Incomplete cross-references across lemmas

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#96]
I have finished translating Thomas (first draft run) and am now working on the grammar classifications to each lemma. I want to ensure that those are consistent as, in my translation, each lemma will have an abbreviated indication of its classification

The first thing that strikes me is that a reference to the description of a lemma is more complete than the description of the lemma itself:

https://coptic-dictionary.org/entry.cgi?tla=C2394 refers to:

cf. ⲡⲱ Poss. Pron. 3.pers. sg. m. cf. ⲧⲱ Poss. Pron. 3. pers. sg. f.

whereas each of those omit the 3rd person:

ⲡⲱ⸗ | S | CF7432 | Poss. Pron. m. sg.
ⲧⲱ⸗ | S | CF10089 | Poss. Pron. f. sg.

Likewise, ⲡⲉ⸗ (https://coptic-dictionary.org/entry.cgi?tla=C2786) refers to:

cf. ⲛⲉ Possessivpräfix pl. cf. ⲧⲉ Possessivpräfix sg. f.

ⲛⲉ⸗ (https://coptic-dictionary.org/entry.cgi?tla=C2384) is okay:

ⲛⲉ⸗ | S | CF6527 | Possessivartikel pl. 1. Pers.

but the search for ⲧⲉ is not exact and only leads to

https://coptic-dictionary.org/entry.cgi?tla=C4007

ⲧⲉ | S | CF9957 | Dem. Pron. Kopula f. sg.

Which is it? German or English? Double hyphen or no hyphen at all? Direct reference to a single lemma or a choice?

Needless to say, person references are superfluous and incorrect here. But that is another matter

**Comment by phoenix-mossimo** [comment]
> cf. ⲡⲱ Poss. Pron. 3.pers. sg. m. cf. ⲧⲱ Poss. Pron. 3. pers. sg. f.
> whereas each of those omit the 3rd person:
> ⲡⲱ⸗ | S | CF7432 | Poss. Pron. m. sg.
> ⲧⲱ⸗ | S | CF10089 | Poss. Pron. f. sg.

Thanks for catching this. ⲡⲱ⸗, ⲧⲱ⸗, ⲛⲟⲩ⸗ refer to the possessed item, thus person information is superfluous here. It is not present in Crum and seems to be the "innovation" of the encoders. Will be corrected as follows: 
- remove `<subc>3. Pers.</subc>` from the `<gramGrp>` element
- remove "3.pers." from the cross-reference 

>ⲛⲉ⸗ (https://coptic-dictionary.org/entry.cgi?tla=C2384) is okay:
> ⲛⲉ⸗ | S | CF6527 | Possessivartikel pl. 1. Pers.
> but the search for ⲧⲉ is not exact and only leads to
> https://coptic-dictionary.org/entry.cgi?tla=C4007
> ⲧⲉ | S | CF9957 | Dem. Pron. Kopula f. sg.

Actually, ⲛⲉ⸗ (C2384) is not OK, "1. Pers." is superfluos and ⲧⲉ⸗ is not there as it is not mentioned in Crum (although its status nominalis form is present: ⲧⲁ-, CD 390a). Will be corrected as follows:
- remove `<subc>1. Pers.</subc>` from the `<gramGrp>` element
- add new entry for the possessive article ⲧⲉ⸗

**Comment by phoenix-mossimo** [comment]
Corrected as follows: 

| Lemma ID  | Spelling |WAS | IS |Comment |
| --- |----- |--------- |--------- |--------- |
| C2394 |ⲛⲟⲩ⸗| `<gramGrp><pos>Poss. Pron.</pos><subc>3. Pers.</subc><number>pl.</number></gramGrp>`  | `<gramGrp><pos>Poss. Pron.</pos><number>pl.</number></gramGrp>` | Removed person information |
| --- |----- |`<ref` target="#ⲡⲱ⸗">Poss. Pron. 3.pers. sg. m.</ref>`|`<ref` target="#ⲡⲱ⸗">Poss. Pron. sg. m.</ref>`| Removed person information |
| --- |----- |`<ref target="#ⲧⲱ⸗">Poss. Pron. 3.pers. sg. f.</ref>`|`<ref` target="#ⲡⲱ⸗">Poss. Pron. sg. f.</ref>`| Removed person information |
| C2798 |ⲡⲱ⸗| `<gramGrp><pos>Poss. Pron.</pos><gen>m.</gen><number>sg.</number></gramGrp>`  | `<gramGrp><pos>Poss. Pron.</pos><gen>m.</gen><number>sg.</number></gramGrp>` | NO CHANGES |
| C4073 |ⲧⲱ⸗| `<gramGrp><pos>Poss. Pron.</pos><gen>f.</gen><number>sg.</number></gramGrp>`  | `<gramGrp><pos>Poss. Pron.</pos><gen>f.</gen><number>sg.</number></gramGrp>` | NO CHANGES |
| C2384|ⲛⲉ⸗| `<gramGrp><pos>Possessivartikel</pos><subc>1. Pers.</subc><number>pl.</number></gramGrp>`  | `<gramGrp><pos>Possessivartikel</pos><number>pl.</number></gramGrp>` | Removed person information |
| C2786 |ⲡⲉ⸗| `<gramGrp><pos>Possessivartikel</pos><gen>m.</gen><number>sg.</number></gramGrp>`  | `<gramGrp><pos>Possessivartikel</pos><gen>m.</gen><number>sg.</number></gramGrp>` | NO CHANGES |
| None |ⲧⲉ⸗| `none`  | `<gramGrp><pos>Possessivartikel</pos><gen>f.</gen><number>sg.</number></gramGrp>` | CREATED A NEW LEMMA |
