### ISSUE TITLE
Broken pointers and inconsistencies across references

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#97]
https://coptic-dictionary.org/entry.cgi?tla=C2787

ⲡⲉ- | B | CF7406 | Possessivartikel 2. Pers. sg. f.

is wrong, this is the entry for masculine. Odd thing is, it points to the masculine for reference:

cf. ⲡⲉ Possessivartikel m. sg.

Please note that it doesn't point to the plural, although one would expect that.
Please also note the order of the words: m. sg. in stead of sg. m.

https://coptic-dictionary.org/entry.cgi?tla=C2384 is the plural and points to both masc and fem, and this now also explains the previous bug I raised: the pointer to the fem. is dead

I am going to call it a day, I think. I just started, and perhaps it is a better idea to collect all issues into one report. The different uses of German and English are confusing, the presence and absence of person indications, sometimes correct and sometimes incorrect - all this is costing me an increasingly incredible amount of time.
I'll wait until your response

**Comment by phoenix-mossimo** [comment]
> https://coptic-dictionary.org/entry.cgi?tla=C2787
> ⲡⲉ- | B | CF7406 | Possessivartikel 2. Pers. sg. f.
> is wrong, this is the entry for masculine. Odd thing is, it points to the masculine for reference:

This is a portmanteau form, which blends the masculine possessive article and possessive pronounof the 2. p. fem. into one word, compare: 
- ⲡⲉ⸗ⲕ-N ("your (masc.) N", in Sahidic)
- ⲡⲟⲩ-N ("your (fem.) N", in Sahidic), accordingly ⲡⲉ-N in Bohairic, Fayyumic etc. This ⲡⲉ- (should be differentiated from possessive ⲡⲉ⸗ (C2786)) is not listed by Crum, but is included in Westendorf as a separate entry (which; I admit, is semantically problematic). I agree there is a problem in grammatical notation.  In ⲡⲉ⸗ (C2786) grammatical information "m. sg." refers to the possessed item, while in ⲡⲉ- "2. Pers. sg. f." refers to the feminine possessor. Considering the fact that the values in `<pos>`, `<subc>`, `<number>` and `<gen>` are a controlled vocabulary, I suggest to add a <note> saying that information in `<subc>`, `<number>` and `<gen>` refers to the possessor. @amir-zeldes can you display such note in the grammar section?

> Please note that it doesn't point to the plural, although one would expect that.

- Correct. Will be corrected as follows: insert cross-reference to C2388 (ⲛⲟⲩ-). Adopt grammatical information in  ⲛⲟⲩ- according to ⲡⲟⲩ-.  Create the entry for feminine ⲧⲟⲩ- 

> Please also note the order of the words: m. sg. in stead of sg. m.

- Correct. 


> https://coptic-dictionary.org/entry.cgi?tla=C2384 is the plural and points to both masc and fem, and this now also explains the previous bug I raised: the pointer to the fem. is dead

- Will be corrected according to the description in #96.

**Comment by phoenix-mossimo** [comment]
We decided to create nested `<gramGrp>` tags, which encode both possessor and possessum information:
 
`<gramGrp>`
`<gramGrp>Possessum</gramGrp>`
`<gramGrp>Possessor</gramGrp>`
`</gramGrp>`

This resembles the Scriptorium portmanteu tags and would correspond to PPOS_PPERS. Scriptorium, however, does not treat possessives as portmanteau forms (i.e. the possessive prefix is not separated from the suffix: ⲡⲉϥ,ⲧⲉⲧⲛ̄). Scriptorium also does not differentiate between possessive pronouns (e.g. ⲡⲱ⸗), articles (e.g. ⲡⲉ⸗) and prefixes (e.g. ⲡⲁ-) - they all have PPOS tag.

For the list of the affected forms and the detailed description of the solution, see https://github.com/KELLIA/dictionary/wiki/Encoding-possessor-%26-possessum-information-with-possessive-pronouns%2C-articles-and-prefixes/

@amir-zeldes Can you take care of the correct rendering of the nested `<gramGrp>`?

**Comment by amir-zeldes** [comment]
OK, I've opened #100 for this - can you push your revised XML so I can see the concrete data?
