### ISSUE TITLE
ⲧⲁϣⲉⲟⲉⲓϣ has two separate entries

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#98]
Probably just a case of me not understanding: please consider

https://coptic-dictionary.org/entry.cgi?tla=C2768
https://coptic-dictionary.org/entry.cgi?tla=C4704

The latter doesn't have a Crum entry, and a slightly different extra meaning (to increase ...).
They point to two different "source verbs" by a cf. reference, perhaps that is why these "are split"?

Perhaps justified, yet I thought to give it a mention - haven't come across a type like this before

**Comment by phoenix-mossimo** [comment]
This is the same compound (ⲧⲁϣⲉ + ⲟⲉⲓϣ), mentioned once by Crum under ⲟⲉⲓϣ, and twice by other dictionaries (under ⲟⲉⲓϣ "cry" and under ⲧⲁϣⲟ "increase"). One entry will be removed.

**Comment by phoenix-mossimo** [comment]
C4704 removed: C2768 includes all the meanings of C2768. The bibliographical information of C2768 extended: `<bibl>CD 257b; CED 122, 202; KoptHWb 140, 255; DELC 224b; ChLCS 36a, 63b</bibl>`
