### ISSUE TITLE
ϣⲡⲏⲣⲉ two entries, odd ANNIS

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#99]
ϣⲡⲏⲣⲉ

https://coptic-dictionary.org/entry.cgi?tla=C6006:

ϣⲡⲏⲣⲉ | S | CF14017 | Subst. f. mostly f.

https://coptic-dictionary.org/entry.cgi?tla=C6007

ϣⲡⲏⲣⲉ | S | CF14019 | Subst. m. mostly f.

Both entries are completely identical save for the f. versus m. - yet the ANNIS entry has 10 in stead of 5, which also are exactly similar between the both. Something seems amiss there?

**Comment by amir-zeldes** [comment]
I don't understand the ANNIS problem: I get the exact same link and 207 matches in ANNIS from either entry (the ANNIS lemma annotations are not gender-aware)

**Comment by m-linssen** [comment]
Ah, I learned something new then (gender-insensitivity in ANNIS). In that case, the entries for both lemmas should indeed be exactly the same

What remains then is the minor issue of 10 entries vs 5: usually, ANNIS has 5 entries, not 10

**Comment by amir-zeldes** [comment]
The lemmas in ANNIS are strings and not unique IDs, so anything with the same form is treated identically in ANNIS. I still don't understand what 10 vs. 5 is referring to: as I said, there are 207 matches, and they are pointed to by both entries in the same way. Where are you seeing 10 and 5?

**Comment by m-linssen** [comment]
Never mind, I thought that 5 was the maximum number of ANNIS refs - it isn't. All set then, sorry, please close

**Comment by amir-zeldes** [comment]
OK, thanks
